import typing_extensions

from zuora_python_sdk.paths import PathValues
from zuora_python_sdk.apis.paths.oauth_token import OauthToken
from zuora_python_sdk.apis.paths.v1_object_product import V1ObjectProduct
from zuora_python_sdk.apis.paths.v1_object_product_id import V1ObjectProductId
from zuora_python_sdk.apis.paths.v1_catalog_products import V1CatalogProducts
from zuora_python_sdk.apis.paths.v1_catalog_products_product_key import V1CatalogProductsProductKey
from zuora_python_sdk.apis.paths.v1_catalog_groups import V1CatalogGroups
from zuora_python_sdk.apis.paths.v1_catalog_groups_catalog_group_key import V1CatalogGroupsCatalogGroupKey
from zuora_python_sdk.apis.paths.v1_products_product_key_product_rate_plans import V1ProductsProductKeyProductRatePlans
from zuora_python_sdk.apis.paths.v1_product_rate_plans_id import V1ProductRatePlansId
from zuora_python_sdk.apis.paths.v1_product_rate_plans_external_id_id import V1ProductRatePlansExternalIdId
from zuora_python_sdk.apis.paths.v1_object_product_rate_plan import V1ObjectProductRatePlan
from zuora_python_sdk.apis.paths.v1_object_product_rate_plan_id import V1ObjectProductRatePlanId
from zuora_python_sdk.apis.paths.v1_product_rateplan_definitions import V1ProductRateplanDefinitions
from zuora_python_sdk.apis.paths.v1_product_rateplan_definitions_product_rateplan_definition_key import V1ProductRateplanDefinitionsProductRateplanDefinitionKey
from zuora_python_sdk.apis.paths.v1_product_rate_plan_charges_product_rate_plan_charge_key import V1ProductRatePlanChargesProductRatePlanChargeKey
from zuora_python_sdk.apis.paths.v1_object_product_rate_plan_charge import V1ObjectProductRatePlanCharge
from zuora_python_sdk.apis.paths.v1_object_product_rate_plan_charge_id import V1ObjectProductRatePlanChargeId
from zuora_python_sdk.apis.paths.v1_product_charge_definitions import V1ProductChargeDefinitions
from zuora_python_sdk.apis.paths.v1_product_charge_definitions_bulk import V1ProductChargeDefinitionsBulk
from zuora_python_sdk.apis.paths.v1_product_charge_definitions_product_charge_definition_key import V1ProductChargeDefinitionsProductChargeDefinitionKey
from zuora_python_sdk.apis.paths.v1_object_product_rate_plan_charge_tier_id import V1ObjectProductRatePlanChargeTierId
from zuora_python_sdk.apis.paths.v1_revpro_accounting_codes import V1RevproAccountingCodes
from zuora_python_sdk.apis.paths.v1_accounts import V1Accounts
from zuora_python_sdk.apis.paths.v1_accounts_account_key import V1AccountsAccountKey
from zuora_python_sdk.apis.paths.v1_accounts_account_key_payment_methods import V1AccountsAccountKeyPaymentMethods
from zuora_python_sdk.apis.paths.v1_accounts_account_key_payment_methods_default import V1AccountsAccountKeyPaymentMethodsDefault
from zuora_python_sdk.apis.paths.v1_accounts_account_key_summary import V1AccountsAccountKeySummary
from zuora_python_sdk.apis.paths.v1_contacts import V1Contacts
from zuora_python_sdk.apis.paths.v1_contacts_contact_id import V1ContactsContactId
from zuora_python_sdk.apis.paths.v1_contacts_contact_id_scrub import V1ContactsContactIdScrub
from zuora_python_sdk.apis.paths.v1_contact_snapshots_contact_snapshot_id import V1ContactSnapshotsContactSnapshotId
from zuora_python_sdk.apis.paths.v1_sign_up import V1SignUp
from zuora_python_sdk.apis.paths.v1_orders_preview import V1OrdersPreview
from zuora_python_sdk.apis.paths.v1_async_orders_preview import V1AsyncOrdersPreview
from zuora_python_sdk.apis.paths.v1_orders import V1Orders
from zuora_python_sdk.apis.paths.v1_async_orders import V1AsyncOrders
from zuora_python_sdk.apis.paths.v1_orders_order_number import V1OrdersOrderNumber
from zuora_python_sdk.apis.paths.v1_async_jobs_job_id import V1AsyncJobsJobId
from zuora_python_sdk.apis.paths.v1_orders_subscription_owner_account_number import V1OrdersSubscriptionOwnerAccountNumber
from zuora_python_sdk.apis.paths.v1_orders_subscription_subscription_number import V1OrdersSubscriptionSubscriptionNumber
from zuora_python_sdk.apis.paths.v1_orders_invoice_owner_account_number import V1OrdersInvoiceOwnerAccountNumber
from zuora_python_sdk.apis.paths.v1_orders_order_number_custom_fields import V1OrdersOrderNumberCustomFields
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_number_custom_fields import V1SubscriptionsSubscriptionNumberCustomFields
from zuora_python_sdk.apis.paths.v1_orders_order_number_trigger_dates import V1OrdersOrderNumberTriggerDates
from zuora_python_sdk.apis.paths.v1_orders_order_number_activate import V1OrdersOrderNumberActivate
from zuora_python_sdk.apis.paths.v1_orders_order_number_cancel import V1OrdersOrderNumberCancel
from zuora_python_sdk.apis.paths.v1_orders_subscription_subscription_key_pending import V1OrdersSubscriptionSubscriptionKeyPending
from zuora_python_sdk.apis.paths.v1_order_actions_id import V1OrderActionsId
from zuora_python_sdk.apis.paths.v1_order_line_items_item_id import V1OrderLineItemsItemId
from zuora_python_sdk.apis.paths.v1_order_line_items_bulk import V1OrderLineItemsBulk
from zuora_python_sdk.apis.paths.v1_fulfillments import V1Fulfillments
from zuora_python_sdk.apis.paths.v1_fulfillments_key import V1FulfillmentsKey
from zuora_python_sdk.apis.paths.v1_fulfillment_items import V1FulfillmentItems
from zuora_python_sdk.apis.paths.v1_fulfillment_items_id import V1FulfillmentItemsId
from zuora_python_sdk.apis.paths.v1_ramps_ramp_number import V1RampsRampNumber
from zuora_python_sdk.apis.paths.v1_ramps_ramp_number_ramp_metrics import V1RampsRampNumberRampMetrics
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_ramps import V1SubscriptionsSubscriptionKeyRamps
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_ramp_metrics import V1SubscriptionsSubscriptionKeyRampMetrics
from zuora_python_sdk.apis.paths.v1_orders_order_number_ramp_metrics import V1OrdersOrderNumberRampMetrics
from zuora_python_sdk.apis.paths.v1_subscriptions_preview import V1SubscriptionsPreview
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_preview import V1SubscriptionsSubscriptionKeyPreview
from zuora_python_sdk.apis.paths.v1_subscriptions import V1Subscriptions
from zuora_python_sdk.apis.paths.v1_subscriptions_accounts_account_key import V1SubscriptionsAccountsAccountKey
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key import V1SubscriptionsSubscriptionKey
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_versions_version import V1SubscriptionsSubscriptionKeyVersionsVersion
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_renew import V1SubscriptionsSubscriptionKeyRenew
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_cancel import V1SubscriptionsSubscriptionKeyCancel
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_resume import V1SubscriptionsSubscriptionKeyResume
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_suspend import V1SubscriptionsSubscriptionKeySuspend
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_key_delete import V1SubscriptionsSubscriptionKeyDelete
from zuora_python_sdk.apis.paths.v1_subscriptions_subscription_number_versions_version_custom_fields import V1SubscriptionsSubscriptionNumberVersionsVersionCustomFields
from zuora_python_sdk.apis.paths.v1_rateplans_rate_plan_id import V1RateplansRatePlanId
from zuora_python_sdk.apis.paths.v1_ppdd_reverse_rollover import V1PpddReverseRollover
from zuora_python_sdk.apis.paths.v1_ppdd_rollover import V1PpddRollover
from zuora_python_sdk.apis.paths.v1_prepaid_balance_funds_deplete import V1PrepaidBalanceFundsDeplete
from zuora_python_sdk.apis.paths.v1_usage import V1Usage
from zuora_python_sdk.apis.paths.v1_usage_accounts_account_key import V1UsageAccountsAccountKey
from zuora_python_sdk.apis.paths.v1_invoices_invoice_item_invoice_item_id_usage_rate_detail import V1InvoicesInvoiceItemInvoiceItemIdUsageRateDetail
from zuora_python_sdk.apis.paths.v1_object_usage import V1ObjectUsage
from zuora_python_sdk.apis.paths.v1_object_usage_id import V1ObjectUsageId
from zuora_python_sdk.apis.paths.v1_adjustments import V1Adjustments
from zuora_python_sdk.apis.paths.v1_adjustments_preview import V1AdjustmentsPreview
from zuora_python_sdk.apis.paths.v1_adjustments_adjustment_key import V1AdjustmentsAdjustmentKey
from zuora_python_sdk.apis.paths.v1_adjustments_adjustment_id_cancel import V1AdjustmentsAdjustmentIdCancel
from zuora_python_sdk.apis.paths.v1_billing_documents import V1BillingDocuments
from zuora_python_sdk.apis.paths.v1_accounts_billing_documents_files_deletion_jobs import V1AccountsBillingDocumentsFilesDeletionJobs
from zuora_python_sdk.apis.paths.v1_accounts_billing_documents_files_deletion_jobs_job_id import V1AccountsBillingDocumentsFilesDeletionJobsJobId
from zuora_python_sdk.apis.paths.v1_accounts_key_billing_documents_generate import V1AccountsKeyBillingDocumentsGenerate
from zuora_python_sdk.apis.paths.v1_invoices import V1Invoices
from zuora_python_sdk.apis.paths.v1_invoices_batch import V1InvoicesBatch
from zuora_python_sdk.apis.paths.v1_invoices_bulk_post import V1InvoicesBulkPost
from zuora_python_sdk.apis.paths.v1_invoices_pdf_status import V1InvoicesPdfStatus
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key import V1InvoicesInvoiceKey
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_application_parts import V1InvoicesInvoiceKeyApplicationParts
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_einvoice_generate import V1InvoicesInvoiceKeyEinvoiceGenerate
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_emails import V1InvoicesInvoiceKeyEmails
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_files import V1InvoicesInvoiceKeyFiles
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_items import V1InvoicesInvoiceKeyItems
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_items_item_id_taxation_items import V1InvoicesInvoiceKeyItemsItemIdTaxationItems
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_reverse import V1InvoicesInvoiceKeyReverse
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_taxationitems import V1InvoicesInvoiceKeyTaxationitems
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_write_off import V1InvoicesInvoiceKeyWriteOff
from zuora_python_sdk.apis.paths.v1_creditmemos import V1Creditmemos
from zuora_python_sdk.apis.paths.v1_creditmemos_bulk import V1CreditmemosBulk
from zuora_python_sdk.apis.paths.v1_creditmemos_pdf_status import V1CreditmemosPdfStatus
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_id_items_cmitemid_taxation_items import V1CreditmemosCreditMemoIdItemsCmitemidTaxationItems
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_id_write_off import V1CreditmemosCreditMemoIdWriteOff
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key import V1CreditmemosCreditMemoKey
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_apply import V1CreditmemosCreditMemoKeyApply
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_cancel import V1CreditmemosCreditMemoKeyCancel
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_einvoice_generate import V1CreditmemosCreditMemoKeyEinvoiceGenerate
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_emails import V1CreditmemosCreditMemoKeyEmails
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_files import V1CreditmemosCreditMemoKeyFiles
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_items import V1CreditmemosCreditMemoKeyItems
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_items_cmitemid import V1CreditmemosCreditMemoKeyItemsCmitemid
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_parts import V1CreditmemosCreditMemoKeyParts
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_parts_partid import V1CreditmemosCreditMemoKeyPartsPartid
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_pdfs import V1CreditmemosCreditMemoKeyPdfs
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_post import V1CreditmemosCreditMemoKeyPost
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_refunds import V1CreditmemosCreditMemoKeyRefunds
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_reverse import V1CreditmemosCreditMemoKeyReverse
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_taxationitems import V1CreditmemosCreditMemoKeyTaxationitems
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_unapply import V1CreditmemosCreditMemoKeyUnapply
from zuora_python_sdk.apis.paths.v1_creditmemos_credit_memo_key_unpost import V1CreditmemosCreditMemoKeyUnpost
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_creditmemos import V1InvoicesInvoiceKeyCreditmemos
from zuora_python_sdk.apis.paths.v1_debitmemos import V1Debitmemos
from zuora_python_sdk.apis.paths.v1_debitmemos_bulk import V1DebitmemosBulk
from zuora_python_sdk.apis.paths.v1_debitmemos_pdf_status import V1DebitmemosPdfStatus
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_id_application_parts import V1DebitmemosDebitMemoIdApplicationParts
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_id_items_dmitemid_taxation_items import V1DebitmemosDebitMemoIdItemsDmitemidTaxationItems
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key import V1DebitmemosDebitMemoKey
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_cancel import V1DebitmemosDebitMemoKeyCancel
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_collect import V1DebitmemosDebitMemoKeyCollect
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_einvoice_generate import V1DebitmemosDebitMemoKeyEinvoiceGenerate
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_emails import V1DebitmemosDebitMemoKeyEmails
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_files import V1DebitmemosDebitMemoKeyFiles
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_items import V1DebitmemosDebitMemoKeyItems
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_items_dmitemid import V1DebitmemosDebitMemoKeyItemsDmitemid
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_pdfs import V1DebitmemosDebitMemoKeyPdfs
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_post import V1DebitmemosDebitMemoKeyPost
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_taxationitems import V1DebitmemosDebitMemoKeyTaxationitems
from zuora_python_sdk.apis.paths.v1_debitmemos_debit_memo_key_unpost import V1DebitmemosDebitMemoKeyUnpost
from zuora_python_sdk.apis.paths.v1_invoices_invoice_key_debitmemos import V1InvoicesInvoiceKeyDebitmemos
from zuora_python_sdk.apis.paths.v1_einvoice_service_providers import V1EinvoiceServiceProviders
from zuora_python_sdk.apis.paths.v1_einvoice_service_providers_key import V1EinvoiceServiceProvidersKey
from zuora_python_sdk.apis.paths.v1_einvoice_business_regions import V1EinvoiceBusinessRegions
from zuora_python_sdk.apis.paths.v1_einvoice_business_regions_key import V1EinvoiceBusinessRegionsKey
from zuora_python_sdk.apis.paths.v1_einvoice_templates import V1EinvoiceTemplates
from zuora_python_sdk.apis.paths.v1_einvoice_templates_key import V1EinvoiceTemplatesKey
from zuora_python_sdk.apis.paths.v1_invoice_schedules import V1InvoiceSchedules
from zuora_python_sdk.apis.paths.v1_invoice_schedules_schedule_key import V1InvoiceSchedulesScheduleKey
from zuora_python_sdk.apis.paths.v1_invoice_schedules_schedule_key_execute import V1InvoiceSchedulesScheduleKeyExecute
from zuora_python_sdk.apis.paths.v1_invoice_schedules_schedule_key_pause import V1InvoiceSchedulesScheduleKeyPause
from zuora_python_sdk.apis.paths.v1_invoice_schedules_schedule_key_resume import V1InvoiceSchedulesScheduleKeyResume
from zuora_python_sdk.apis.paths.v1_object_taxation_item import V1ObjectTaxationItem
from zuora_python_sdk.apis.paths.v1_taxationitems_id import V1TaxationitemsId
from zuora_python_sdk.apis.paths.v1_sequence_sets import V1SequenceSets
from zuora_python_sdk.apis.paths.v1_sequence_sets_id import V1SequenceSetsId
from zuora_python_sdk.apis.paths.v1_operations_billing_preview import V1OperationsBillingPreview
from zuora_python_sdk.apis.paths.v1_operations_invoice_collect import V1OperationsInvoiceCollect
from zuora_python_sdk.apis.paths.v1_operations_jobs_job_id import V1OperationsJobsJobId
from zuora_python_sdk.apis.paths.v1_operations_bulk_pdf import V1OperationsBulkPdf
from zuora_python_sdk.apis.paths.v1_operations_bulk_pdf_job_id import V1OperationsBulkPdfJobId
from zuora_python_sdk.apis.paths.v1_bill_runs import V1BillRuns
from zuora_python_sdk.apis.paths.v1_bill_runs_bill_run_id import V1BillRunsBillRunId
from zuora_python_sdk.apis.paths.v1_bill_runs_bill_run_id_cancel import V1BillRunsBillRunIdCancel
from zuora_python_sdk.apis.paths.v1_bill_runs_bill_run_id_post import V1BillRunsBillRunIdPost
from zuora_python_sdk.apis.paths.v1_bill_runs_bill_run_key_emails import V1BillRunsBillRunKeyEmails
from zuora_python_sdk.apis.paths.v1_billing_preview_runs import V1BillingPreviewRuns
from zuora_python_sdk.apis.paths.v1_billing_preview_runs_billing_preview_run_id import V1BillingPreviewRunsBillingPreviewRunId
from zuora_python_sdk.apis.paths.v1_payment_methods import V1PaymentMethods
from zuora_python_sdk.apis.paths.v1_payment_methods_decryption import V1PaymentMethodsDecryption
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id import V1PaymentMethodsPaymentMethodId
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_verify import V1PaymentMethodsPaymentMethodIdVerify
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_scrub import V1PaymentMethodsPaymentMethodIdScrub
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_profiles import V1PaymentMethodsPaymentMethodIdProfiles
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_profiles_profile_number_cancel import V1PaymentMethodsPaymentMethodIdProfilesProfileNumberCancel
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_profiles_profile_number_expire import V1PaymentMethodsPaymentMethodIdProfilesProfileNumberExpire
from zuora_python_sdk.apis.paths.payment_methods_apple_pay_domains import PaymentMethodsApplePayDomains
from zuora_python_sdk.apis.paths.payment_methods_apple_pay_domains_id import PaymentMethodsApplePayDomainsId
from zuora_python_sdk.apis.paths.web_payments_sessions import WebPaymentsSessions
from zuora_python_sdk.apis.paths.v1_object_payment_method_snapshot_id import V1ObjectPaymentMethodSnapshotId
from zuora_python_sdk.apis.paths.v1_object_payment_method_transaction_log_id import V1ObjectPaymentMethodTransactionLogId
from zuora_python_sdk.apis.paths.v1_payment_method_updaters import V1PaymentMethodUpdaters
from zuora_python_sdk.apis.paths.v1_payment_method_updaters_batches import V1PaymentMethodUpdatersBatches
from zuora_python_sdk.apis.paths.v1_rsa_signatures import V1RsaSignatures
from zuora_python_sdk.apis.paths.v1_rsa_signatures_decrypt import V1RsaSignaturesDecrypt
from zuora_python_sdk.apis.paths.v1_hostedpages import V1Hostedpages
from zuora_python_sdk.apis.paths.open_payment_method_types import OpenPaymentMethodTypes
from zuora_python_sdk.apis.paths.open_payment_method_types_publish_payment_method_type_name import OpenPaymentMethodTypesPublishPaymentMethodTypeName
from zuora_python_sdk.apis.paths.open_payment_method_types_payment_method_type_name import OpenPaymentMethodTypesPaymentMethodTypeName
from zuora_python_sdk.apis.paths.open_payment_method_types_payment_method_type_name_draft_revision_number import OpenPaymentMethodTypesPaymentMethodTypeNameDraftRevisionNumber
from zuora_python_sdk.apis.paths.open_payment_method_types_payment_method_type_name_published import OpenPaymentMethodTypesPaymentMethodTypeNamePublished
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_authorize import V1PaymentMethodsPaymentMethodIdAuthorize
from zuora_python_sdk.apis.paths.v1_payment_methods_payment_method_id_void_authorize import V1PaymentMethodsPaymentMethodIdVoidAuthorize
from zuora_python_sdk.apis.paths.v1_paymentgateways import V1Paymentgateways
from zuora_python_sdk.apis.paths.v1_gateway_settlement_payments_payment_key_chargeback import V1GatewaySettlementPaymentsPaymentKeyChargeback
from zuora_python_sdk.apis.paths.v1_gateway_settlement_payments_payment_key_reject import V1GatewaySettlementPaymentsPaymentKeyReject
from zuora_python_sdk.apis.paths.v1_gateway_settlement_payments_payment_key_settle import V1GatewaySettlementPaymentsPaymentKeySettle
from zuora_python_sdk.apis.paths.v1_refunds_refund_key_reconcile import V1RefundsRefundKeyReconcile
from zuora_python_sdk.apis.paths.v1_payments import V1Payments
from zuora_python_sdk.apis.paths.v1_payments_payment_id import V1PaymentsPaymentId
from zuora_python_sdk.apis.paths.v1_payments_payment_key import V1PaymentsPaymentKey
from zuora_python_sdk.apis.paths.v1_payments_payment_key_apply import V1PaymentsPaymentKeyApply
from zuora_python_sdk.apis.paths.v1_payments_payment_key_cancel import V1PaymentsPaymentKeyCancel
from zuora_python_sdk.apis.paths.v1_payments_payment_key_parts import V1PaymentsPaymentKeyParts
from zuora_python_sdk.apis.paths.v1_payments_payment_key_parts_partid import V1PaymentsPaymentKeyPartsPartid
from zuora_python_sdk.apis.paths.v1_payments_payment_key_parts_partid_itemparts import V1PaymentsPaymentKeyPartsPartidItemparts
from zuora_python_sdk.apis.paths.v1_payments_payment_key_parts_partid_itemparts_itempartid import V1PaymentsPaymentKeyPartsPartidItempartsItempartid
from zuora_python_sdk.apis.paths.v1_payments_payment_key_refunds import V1PaymentsPaymentKeyRefunds
from zuora_python_sdk.apis.paths.v1_payments_payment_key_refunds_unapply import V1PaymentsPaymentKeyRefundsUnapply
from zuora_python_sdk.apis.paths.v1_payments_payment_key_transfer import V1PaymentsPaymentKeyTransfer
from zuora_python_sdk.apis.paths.v1_payments_payment_key_unapply import V1PaymentsPaymentKeyUnapply
from zuora_python_sdk.apis.paths.v1_object_payment_transaction_log_id import V1ObjectPaymentTransactionLogId
from zuora_python_sdk.apis.paths.v1_payment_runs import V1PaymentRuns
from zuora_python_sdk.apis.paths.v1_payment_runs_payment_run_key import V1PaymentRunsPaymentRunKey
from zuora_python_sdk.apis.paths.v1_payment_runs_payment_run_key_data import V1PaymentRunsPaymentRunKeyData
from zuora_python_sdk.apis.paths.v1_payment_runs_payment_run_key_summary import V1PaymentRunsPaymentRunKeySummary
from zuora_python_sdk.apis.paths.v1_payment_schedule_items_retry_payment import V1PaymentScheduleItemsRetryPayment
from zuora_python_sdk.apis.paths.v1_payment_schedule_items_item_id import V1PaymentScheduleItemsItemId
from zuora_python_sdk.apis.paths.v1_payment_schedule_items_item_id_cancel import V1PaymentScheduleItemsItemIdCancel
from zuora_python_sdk.apis.paths.v1_payment_schedule_items_item_id_skip import V1PaymentScheduleItemsItemIdSkip
from zuora_python_sdk.apis.paths.v1_payment_schedules import V1PaymentSchedules
from zuora_python_sdk.apis.paths.v1_payment_schedules_batch import V1PaymentSchedulesBatch
from zuora_python_sdk.apis.paths.v1_payment_schedules_statistics_yyyy_mm_dd import V1PaymentSchedulesStatisticsYyyyMmDd
from zuora_python_sdk.apis.paths.v1_payment_schedules_payment_schedule_key import V1PaymentSchedulesPaymentScheduleKey
from zuora_python_sdk.apis.paths.v1_payment_schedules_payment_schedule_key_cancel import V1PaymentSchedulesPaymentScheduleKeyCancel
from zuora_python_sdk.apis.paths.v1_payment_schedules_payment_schedule_key_items import V1PaymentSchedulesPaymentScheduleKeyItems
from zuora_python_sdk.apis.paths.v1_payment_schedules_payment_schedule_key_preview import V1PaymentSchedulesPaymentScheduleKeyPreview
from zuora_python_sdk.apis.paths.v1_refunds import V1Refunds
from zuora_python_sdk.apis.paths.v1_refunds_refund_id import V1RefundsRefundId
from zuora_python_sdk.apis.paths.v1_refunds_refund_key import V1RefundsRefundKey
from zuora_python_sdk.apis.paths.v1_refunds_refund_key_cancel import V1RefundsRefundKeyCancel
from zuora_python_sdk.apis.paths.v1_refunds_refund_key_parts import V1RefundsRefundKeyParts
from zuora_python_sdk.apis.paths.v1_refunds_refund_key_parts_refundpartid import V1RefundsRefundKeyPartsRefundpartid
from zuora_python_sdk.apis.paths.v1_refunds_refund_key_parts_refundpartid_itemparts import V1RefundsRefundKeyPartsRefundpartidItemparts
from zuora_python_sdk.apis.paths.v1_refunds_refund_key_parts_refundpartid_itemparts_itempartid import V1RefundsRefundKeyPartsRefundpartidItempartsItempartid
from zuora_python_sdk.apis.paths.v1_accounting_codes import V1AccountingCodes
from zuora_python_sdk.apis.paths.v1_accounting_codes_ac_id import V1AccountingCodesAcId
from zuora_python_sdk.apis.paths.v1_accounting_codes_ac_id_activate import V1AccountingCodesAcIdActivate
from zuora_python_sdk.apis.paths.v1_accounting_codes_ac_id_deactivate import V1AccountingCodesAcIdDeactivate
from zuora_python_sdk.apis.paths.v1_accounting_periods import V1AccountingPeriods
from zuora_python_sdk.apis.paths.v1_accounting_periods_ap_id import V1AccountingPeriodsApId
from zuora_python_sdk.apis.paths.v1_accounting_periods_ap_id_close import V1AccountingPeriodsApIdClose
from zuora_python_sdk.apis.paths.v1_accounting_periods_ap_id_pending_close import V1AccountingPeriodsApIdPendingClose
from zuora_python_sdk.apis.paths.v1_accounting_periods_ap_id_reopen import V1AccountingPeriodsApIdReopen
from zuora_python_sdk.apis.paths.v1_accounting_periods_ap_id_run_trial_balance import V1AccountingPeriodsApIdRunTrialBalance
from zuora_python_sdk.apis.paths.v1_journal_entries import V1JournalEntries
from zuora_python_sdk.apis.paths.v1_journal_entries_journal_runs_jr_number import V1JournalEntriesJournalRunsJrNumber
from zuora_python_sdk.apis.paths.v1_journal_entries_je_number import V1JournalEntriesJeNumber
from zuora_python_sdk.apis.paths.v1_journal_entries_je_number_basic_information import V1JournalEntriesJeNumberBasicInformation
from zuora_python_sdk.apis.paths.v1_journal_entries_je_number_cancel import V1JournalEntriesJeNumberCancel
from zuora_python_sdk.apis.paths.v1_journal_runs import V1JournalRuns
from zuora_python_sdk.apis.paths.v1_journal_runs_jr_number import V1JournalRunsJrNumber
from zuora_python_sdk.apis.paths.v1_journal_runs_jr_number_cancel import V1JournalRunsJrNumberCancel
from zuora_python_sdk.apis.paths.v1_bulk import V1Bulk
from zuora_python_sdk.apis.paths.v1_bulk_bulk_key import V1BulkBulkKey
from zuora_python_sdk.apis.paths.v1_bulk_bulk_key_stop import V1BulkBulkKeyStop
from zuora_python_sdk.apis.paths.events_event_triggers import EventsEventTriggers
from zuora_python_sdk.apis.paths.events_event_triggers_id import EventsEventTriggersId
from zuora_python_sdk.apis.paths.events_scheduled_events import EventsScheduledEvents
from zuora_python_sdk.apis.paths.events_scheduled_events_id import EventsScheduledEventsId
from zuora_python_sdk.apis.paths.notifications_notification_definitions import NotificationsNotificationDefinitions
from zuora_python_sdk.apis.paths.notifications_notification_definitions_id import NotificationsNotificationDefinitionsId
from zuora_python_sdk.apis.paths.notifications_email_templates_import import NotificationsEmailTemplatesImport
from zuora_python_sdk.apis.paths.notifications_email_templates import NotificationsEmailTemplates
from zuora_python_sdk.apis.paths.notifications_email_templates_id import NotificationsEmailTemplatesId
from zuora_python_sdk.apis.paths.notifications_history import NotificationsHistory
from zuora_python_sdk.apis.paths.notifications_history_tasks_id import NotificationsHistoryTasksId
from zuora_python_sdk.apis.paths.notifications_callout_histories_resend import NotificationsCalloutHistoriesResend
from zuora_python_sdk.apis.paths.notifications_email_histories_resend import NotificationsEmailHistoriesResend
from zuora_python_sdk.apis.paths.v1_notification_history_callout import V1NotificationHistoryCallout
from zuora_python_sdk.apis.paths.v1_notification_history_email import V1NotificationHistoryEmail
from zuora_python_sdk.apis.paths.objects_definitions_default import ObjectsDefinitionsDefault
from zuora_python_sdk.apis.paths.objects_migrations import ObjectsMigrations
from zuora_python_sdk.apis.paths.objects_definitions_default_object import ObjectsDefinitionsDefaultObject
from zuora_python_sdk.apis.paths.objects_records_default_object import ObjectsRecordsDefaultObject
from zuora_python_sdk.apis.paths.objects_records_default_object_id import ObjectsRecordsDefaultObjectId
from zuora_python_sdk.apis.paths.objects_batch_default_object import ObjectsBatchDefaultObject
from zuora_python_sdk.apis.paths.objects_jobs import ObjectsJobs
from zuora_python_sdk.apis.paths.objects_jobs_id import ObjectsJobsId
from zuora_python_sdk.apis.paths.objects_jobs_id_files import ObjectsJobsIdFiles
from zuora_python_sdk.apis.paths.objects_jobs_id_errors import ObjectsJobsIdErrors
from zuora_python_sdk.apis.paths.objects_jobs_id_cancel import ObjectsJobsIdCancel
from zuora_python_sdk.apis.paths.system_health_api_requests_volume_summary import SystemHealthApiRequestsVolumeSummary
from zuora_python_sdk.apis.paths.system_health_billing_documents_volume_summary import SystemHealthBillingDocumentsVolumeSummary
from zuora_python_sdk.apis.paths.system_health_payments_volume_summary import SystemHealthPaymentsVolumeSummary
from zuora_python_sdk.apis.paths.versions_version_id import VersionsVersionId
from zuora_python_sdk.apis.paths.workflows import Workflows
from zuora_python_sdk.apis.paths.workflows_import import WorkflowsImport
from zuora_python_sdk.apis.paths.workflows_metrics_json import WorkflowsMetricsJson
from zuora_python_sdk.apis.paths.workflows_tasks import WorkflowsTasks
from zuora_python_sdk.apis.paths.workflows_tasks_batch_update import WorkflowsTasksBatchUpdate
from zuora_python_sdk.apis.paths.workflows_tasks_task_id import WorkflowsTasksTaskId
from zuora_python_sdk.apis.paths.workflows_tasks_task_id_rerun import WorkflowsTasksTaskIdRerun
from zuora_python_sdk.apis.paths.workflows_workflow_runs_workflow_run_id import WorkflowsWorkflowRunsWorkflowRunId
from zuora_python_sdk.apis.paths.workflows_workflow_id import WorkflowsWorkflowId
from zuora_python_sdk.apis.paths.workflows_workflow_id_export import WorkflowsWorkflowIdExport
from zuora_python_sdk.apis.paths.workflows_workflow_id_run import WorkflowsWorkflowIdRun
from zuora_python_sdk.apis.paths.workflows_workflow_id_versions import WorkflowsWorkflowIdVersions
from zuora_python_sdk.apis.paths.workflows_workflow_id_versions_import import WorkflowsWorkflowIdVersionsImport
from zuora_python_sdk.apis.paths.workflows_workflow_runs_workflow_run_id_stop import WorkflowsWorkflowRunsWorkflowRunIdStop
from zuora_python_sdk.apis.paths.query_jobs import QueryJobs
from zuora_python_sdk.apis.paths.query_jobs_job_id import QueryJobsJobId
from zuora_python_sdk.apis.paths.v1_batch_query_jobs_partner_partner_project_project import V1BatchQueryJobsPartnerPartnerProjectProject
from zuora_python_sdk.apis.paths.v1_batch_query_jobs_jobid import V1BatchQueryJobsJobid
from zuora_python_sdk.apis.paths.deployment_manager_deployment_artifacts import DeploymentManagerDeploymentArtifacts
from zuora_python_sdk.apis.paths.deployment_manager_deployment_artifacts_compare import DeploymentManagerDeploymentArtifactsCompare
from zuora_python_sdk.apis.paths.deployment_manager_deployment_artifacts_deploy import DeploymentManagerDeploymentArtifactsDeploy
from zuora_python_sdk.apis.paths.deployment_manager_deployment_artifacts_retrieve_settings import DeploymentManagerDeploymentArtifactsRetrieveSettings
from zuora_python_sdk.apis.paths.deployment_manager_deployment_templates import DeploymentManagerDeploymentTemplates
from zuora_python_sdk.apis.paths.deployment_manager_deployment_templates_id import DeploymentManagerDeploymentTemplatesId
from zuora_python_sdk.apis.paths.deployment_manager_deployments_tenants import DeploymentManagerDeploymentsTenants
from zuora_python_sdk.apis.paths.deployment_manager_deployments_templates import DeploymentManagerDeploymentsTemplates
from zuora_python_sdk.apis.paths.deployment_manager_deployments_migration_id_revert import DeploymentManagerDeploymentsMigrationIdRevert
from zuora_python_sdk.apis.paths.deployment_manager_deployments_migration_id import DeploymentManagerDeploymentsMigrationId
from zuora_python_sdk.apis.paths.deployment_manager_deployments_tenant_product_catalog import DeploymentManagerDeploymentsTenantProductCatalog
from zuora_python_sdk.apis.paths.deployment_manager_deployments_template_product_catalog import DeploymentManagerDeploymentsTemplateProductCatalog
from zuora_python_sdk.apis.paths.v1_multi_organizations_data_labeling_job import V1MultiOrganizationsDataLabelingJob
from zuora_python_sdk.apis.paths.v1_multi_organizations_data_labeling_job_job_id import V1MultiOrganizationsDataLabelingJobJobId
from zuora_python_sdk.apis.paths.v1_uno_regenerate_booking_transaction import V1UnoRegenerateBookingTransaction
from zuora_python_sdk.apis.paths.v1_uno_regenerate_billing_transaction import V1UnoRegenerateBillingTransaction
from zuora_python_sdk.apis.paths.v1_uno_regenerate_rev_rec_events import V1UnoRegenerateRevRecEvents
from zuora_python_sdk.apis.paths.v1_uno_regenerate_rev_rec_events_daily_consumption import V1UnoRegenerateRevRecEventsDailyConsumption
from zuora_python_sdk.apis.paths.v1_uno_data_backfill_bookingdate_jobs import V1UnoDataBackfillBookingdateJobs
from zuora_python_sdk.apis.paths.v1_uno_data_backfill_bookingdate_jobs_job_id import V1UnoDataBackfillBookingdateJobsJobId
from zuora_python_sdk.apis.paths.v1_uno_data_backfill_jobs import V1UnoDataBackfillJobs
from zuora_python_sdk.apis.paths.v1_uno_data_backfill_jobs_job_id import V1UnoDataBackfillJobsJobId
from zuora_python_sdk.apis.paths.v1_uno_data_backfill_listjobs import V1UnoDataBackfillListjobs
from zuora_python_sdk.apis.paths.v1_uno_back_fill_jobs_type_template import V1UnoBackFillJobsTypeTemplate
from zuora_python_sdk.apis.paths.v1_action_create import V1ActionCreate
from zuora_python_sdk.apis.paths.v1_action_delete import V1ActionDelete
from zuora_python_sdk.apis.paths.v1_action_query import V1ActionQuery
from zuora_python_sdk.apis.paths.v1_action_query_more import V1ActionQueryMore
from zuora_python_sdk.apis.paths.v1_action_update import V1ActionUpdate
from zuora_python_sdk.apis.paths.settings_batch_requests import SettingsBatchRequests
from zuora_python_sdk.apis.paths.settings_listing import SettingsListing
from zuora_python_sdk.apis.paths.v1_files_file_id import V1FilesFileId
from zuora_python_sdk.apis.paths.v1_object_import import V1ObjectImport
from zuora_python_sdk.apis.paths.v1_object_import_id import V1ObjectImportId
from zuora_python_sdk.apis.paths.v1_custom_exchange_rates_currency import V1CustomExchangeRatesCurrency
from zuora_python_sdk.apis.paths.v1_attachments import V1Attachments
from zuora_python_sdk.apis.paths.v1_attachments_attachment_id import V1AttachmentsAttachmentId
from zuora_python_sdk.apis.paths.v1_attachments_object_type_object_key import V1AttachmentsObjectTypeObjectKey
from zuora_python_sdk.apis.paths.v1_describe_object import V1DescribeObject
from zuora_python_sdk.apis.paths.v1_batch_query import V1BatchQuery

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.OAUTH_TOKEN: OauthToken,
        PathValues.V1_OBJECT_PRODUCT: V1ObjectProduct,
        PathValues.V1_OBJECT_PRODUCT_ID: V1ObjectProductId,
        PathValues.V1_CATALOG_PRODUCTS: V1CatalogProducts,
        PathValues.V1_CATALOG_PRODUCTS_PRODUCTKEY: V1CatalogProductsProductKey,
        PathValues.V1_CATALOGGROUPS: V1CatalogGroups,
        PathValues.V1_CATALOGGROUPS_CATALOGGROUPKEY: V1CatalogGroupsCatalogGroupKey,
        PathValues.V1_PRODUCTS_PRODUCTKEY_PRODUCTRATEPLANS: V1ProductsProductKeyProductRatePlans,
        PathValues.V1_PRODUCTRATEPLANS_ID: V1ProductRatePlansId,
        PathValues.V1_PRODUCTRATEPLANS_EXTERNALID_ID: V1ProductRatePlansExternalIdId,
        PathValues.V1_OBJECT_PRODUCTRATEPLAN: V1ObjectProductRatePlan,
        PathValues.V1_OBJECT_PRODUCTRATEPLAN_ID: V1ObjectProductRatePlanId,
        PathValues.V1_PRODUCTRATEPLANDEFINITIONS: V1ProductRateplanDefinitions,
        PathValues.V1_PRODUCTRATEPLANDEFINITIONS_PRODUCTRATEPLANDEFINITIONKEY: V1ProductRateplanDefinitionsProductRateplanDefinitionKey,
        PathValues.V1_PRODUCTRATEPLANCHARGES_PRODUCTRATEPLANCHARGEKEY: V1ProductRatePlanChargesProductRatePlanChargeKey,
        PathValues.V1_OBJECT_PRODUCTRATEPLANCHARGE: V1ObjectProductRatePlanCharge,
        PathValues.V1_OBJECT_PRODUCTRATEPLANCHARGE_ID: V1ObjectProductRatePlanChargeId,
        PathValues.V1_PRODUCTCHARGEDEFINITIONS: V1ProductChargeDefinitions,
        PathValues.V1_PRODUCTCHARGEDEFINITIONS_BULK: V1ProductChargeDefinitionsBulk,
        PathValues.V1_PRODUCTCHARGEDEFINITIONS_PRODUCTCHARGEDEFINITIONKEY: V1ProductChargeDefinitionsProductChargeDefinitionKey,
        PathValues.V1_OBJECT_PRODUCTRATEPLANCHARGETIER_ID: V1ObjectProductRatePlanChargeTierId,
        PathValues.V1_REVPROACCOUNTINGCODES: V1RevproAccountingCodes,
        PathValues.V1_ACCOUNTS: V1Accounts,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY: V1AccountsAccountKey,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY_PAYMENTMETHODS: V1AccountsAccountKeyPaymentMethods,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY_PAYMENTMETHODS_DEFAULT: V1AccountsAccountKeyPaymentMethodsDefault,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY_SUMMARY: V1AccountsAccountKeySummary,
        PathValues.V1_CONTACTS: V1Contacts,
        PathValues.V1_CONTACTS_CONTACT_ID: V1ContactsContactId,
        PathValues.V1_CONTACTS_CONTACT_ID_SCRUB: V1ContactsContactIdScrub,
        PathValues.V1_CONTACTSNAPSHOTS_CONTACTSNAPSHOTID: V1ContactSnapshotsContactSnapshotId,
        PathValues.V1_SIGNUP: V1SignUp,
        PathValues.V1_ORDERS_PREVIEW: V1OrdersPreview,
        PathValues.V1_ASYNC_ORDERS_PREVIEW: V1AsyncOrdersPreview,
        PathValues.V1_ORDERS: V1Orders,
        PathValues.V1_ASYNC_ORDERS: V1AsyncOrders,
        PathValues.V1_ORDERS_ORDER_NUMBER: V1OrdersOrderNumber,
        PathValues.V1_ASYNCJOBS_JOB_ID: V1AsyncJobsJobId,
        PathValues.V1_ORDERS_SUBSCRIPTION_OWNER_ACCOUNT_NUMBER: V1OrdersSubscriptionOwnerAccountNumber,
        PathValues.V1_ORDERS_SUBSCRIPTION_SUBSCRIPTION_NUMBER: V1OrdersSubscriptionSubscriptionNumber,
        PathValues.V1_ORDERS_INVOICE_OWNER_ACCOUNT_NUMBER: V1OrdersInvoiceOwnerAccountNumber,
        PathValues.V1_ORDERS_ORDER_NUMBER_CUSTOM_FIELDS: V1OrdersOrderNumberCustomFields,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_NUMBER_CUSTOM_FIELDS: V1SubscriptionsSubscriptionNumberCustomFields,
        PathValues.V1_ORDERS_ORDER_NUMBER_TRIGGER_DATES: V1OrdersOrderNumberTriggerDates,
        PathValues.V1_ORDERS_ORDER_NUMBER_ACTIVATE: V1OrdersOrderNumberActivate,
        PathValues.V1_ORDERS_ORDER_NUMBER_CANCEL: V1OrdersOrderNumberCancel,
        PathValues.V1_ORDERS_SUBSCRIPTION_SUBSCRIPTIONKEY_PENDING: V1OrdersSubscriptionSubscriptionKeyPending,
        PathValues.V1_ORDER_ACTIONS_ID: V1OrderActionsId,
        PathValues.V1_ORDERLINEITEMS_ITEM_ID: V1OrderLineItemsItemId,
        PathValues.V1_ORDERLINEITEMS_BULK: V1OrderLineItemsBulk,
        PathValues.V1_FULFILLMENTS: V1Fulfillments,
        PathValues.V1_FULFILLMENTS_KEY: V1FulfillmentsKey,
        PathValues.V1_FULFILLMENTITEMS: V1FulfillmentItems,
        PathValues.V1_FULFILLMENTITEMS_ID: V1FulfillmentItemsId,
        PathValues.V1_RAMPS_RAMP_NUMBER: V1RampsRampNumber,
        PathValues.V1_RAMPS_RAMP_NUMBER_RAMPMETRICS: V1RampsRampNumberRampMetrics,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_KEY_RAMPS: V1SubscriptionsSubscriptionKeyRamps,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_KEY_RAMPMETRICS: V1SubscriptionsSubscriptionKeyRampMetrics,
        PathValues.V1_ORDERS_ORDER_NUMBER_RAMPMETRICS: V1OrdersOrderNumberRampMetrics,
        PathValues.V1_SUBSCRIPTIONS_PREVIEW: V1SubscriptionsPreview,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_PREVIEW: V1SubscriptionsSubscriptionKeyPreview,
        PathValues.V1_SUBSCRIPTIONS: V1Subscriptions,
        PathValues.V1_SUBSCRIPTIONS_ACCOUNTS_ACCOUNTKEY: V1SubscriptionsAccountsAccountKey,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY: V1SubscriptionsSubscriptionKey,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_VERSIONS_VERSION: V1SubscriptionsSubscriptionKeyVersionsVersion,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_RENEW: V1SubscriptionsSubscriptionKeyRenew,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_CANCEL: V1SubscriptionsSubscriptionKeyCancel,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_RESUME: V1SubscriptionsSubscriptionKeyResume,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_SUSPEND: V1SubscriptionsSubscriptionKeySuspend,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_DELETE: V1SubscriptionsSubscriptionKeyDelete,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_NUMBER_VERSIONS_VERSION_CUSTOM_FIELDS: V1SubscriptionsSubscriptionNumberVersionsVersionCustomFields,
        PathValues.V1_RATEPLANS_RATE_PLAN_ID: V1RateplansRatePlanId,
        PathValues.V1_PPDD_REVERSEROLLOVER: V1PpddReverseRollover,
        PathValues.V1_PPDD_ROLLOVER: V1PpddRollover,
        PathValues.V1_PREPAIDBALANCEFUNDS_DEPLETE: V1PrepaidBalanceFundsDeplete,
        PathValues.V1_USAGE: V1Usage,
        PathValues.V1_USAGE_ACCOUNTS_ACCOUNTKEY: V1UsageAccountsAccountKey,
        PathValues.V1_INVOICES_INVOICEITEM_INVOICEITEMID_USAGERATEDETAIL: V1InvoicesInvoiceItemInvoiceItemIdUsageRateDetail,
        PathValues.V1_OBJECT_USAGE: V1ObjectUsage,
        PathValues.V1_OBJECT_USAGE_ID: V1ObjectUsageId,
        PathValues.V1_ADJUSTMENTS: V1Adjustments,
        PathValues.V1_ADJUSTMENTS_PREVIEW: V1AdjustmentsPreview,
        PathValues.V1_ADJUSTMENTS_ADJUSTMENTKEY: V1AdjustmentsAdjustmentKey,
        PathValues.V1_ADJUSTMENTS_ADJUSTMENT_ID_CANCEL: V1AdjustmentsAdjustmentIdCancel,
        PathValues.V1_BILLINGDOCUMENTS: V1BillingDocuments,
        PathValues.V1_ACCOUNTS_BILLINGDOCUMENTS_FILES_DELETIONJOBS: V1AccountsBillingDocumentsFilesDeletionJobs,
        PathValues.V1_ACCOUNTS_BILLINGDOCUMENTS_FILES_DELETIONJOBS_JOB_ID: V1AccountsBillingDocumentsFilesDeletionJobsJobId,
        PathValues.V1_ACCOUNTS_KEY_BILLINGDOCUMENTS_GENERATE: V1AccountsKeyBillingDocumentsGenerate,
        PathValues.V1_INVOICES: V1Invoices,
        PathValues.V1_INVOICES_BATCH: V1InvoicesBatch,
        PathValues.V1_INVOICES_BULKPOST: V1InvoicesBulkPost,
        PathValues.V1_INVOICES_PDFSTATUS: V1InvoicesPdfStatus,
        PathValues.V1_INVOICES_INVOICE_KEY: V1InvoicesInvoiceKey,
        PathValues.V1_INVOICES_INVOICE_KEY_APPLICATIONPARTS: V1InvoicesInvoiceKeyApplicationParts,
        PathValues.V1_INVOICES_INVOICE_KEY_EINVOICE_GENERATE: V1InvoicesInvoiceKeyEinvoiceGenerate,
        PathValues.V1_INVOICES_INVOICE_KEY_EMAILS: V1InvoicesInvoiceKeyEmails,
        PathValues.V1_INVOICES_INVOICE_KEY_FILES: V1InvoicesInvoiceKeyFiles,
        PathValues.V1_INVOICES_INVOICE_KEY_ITEMS: V1InvoicesInvoiceKeyItems,
        PathValues.V1_INVOICES_INVOICE_KEY_ITEMS_ITEM_ID_TAXATIONITEMS: V1InvoicesInvoiceKeyItemsItemIdTaxationItems,
        PathValues.V1_INVOICES_INVOICE_KEY_REVERSE: V1InvoicesInvoiceKeyReverse,
        PathValues.V1_INVOICES_INVOICE_KEY_TAXATIONITEMS: V1InvoicesInvoiceKeyTaxationitems,
        PathValues.V1_INVOICES_INVOICE_KEY_WRITEOFF: V1InvoicesInvoiceKeyWriteOff,
        PathValues.V1_CREDITMEMOS: V1Creditmemos,
        PathValues.V1_CREDITMEMOS_BULK: V1CreditmemosBulk,
        PathValues.V1_CREDITMEMOS_PDFSTATUS: V1CreditmemosPdfStatus,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_ID_ITEMS_CMITEMID_TAXATIONITEMS: V1CreditmemosCreditMemoIdItemsCmitemidTaxationItems,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_ID_WRITEOFF: V1CreditmemosCreditMemoIdWriteOff,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY: V1CreditmemosCreditMemoKey,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_APPLY: V1CreditmemosCreditMemoKeyApply,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_CANCEL: V1CreditmemosCreditMemoKeyCancel,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_EINVOICE_GENERATE: V1CreditmemosCreditMemoKeyEinvoiceGenerate,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_EMAILS: V1CreditmemosCreditMemoKeyEmails,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_FILES: V1CreditmemosCreditMemoKeyFiles,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_ITEMS: V1CreditmemosCreditMemoKeyItems,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_ITEMS_CMITEMID: V1CreditmemosCreditMemoKeyItemsCmitemid,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_PARTS: V1CreditmemosCreditMemoKeyParts,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_PARTS_PARTID: V1CreditmemosCreditMemoKeyPartsPartid,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_PDFS: V1CreditmemosCreditMemoKeyPdfs,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_POST: V1CreditmemosCreditMemoKeyPost,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_REFUNDS: V1CreditmemosCreditMemoKeyRefunds,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_REVERSE: V1CreditmemosCreditMemoKeyReverse,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_TAXATIONITEMS: V1CreditmemosCreditMemoKeyTaxationitems,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_UNAPPLY: V1CreditmemosCreditMemoKeyUnapply,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_UNPOST: V1CreditmemosCreditMemoKeyUnpost,
        PathValues.V1_INVOICES_INVOICE_KEY_CREDITMEMOS: V1InvoicesInvoiceKeyCreditmemos,
        PathValues.V1_DEBITMEMOS: V1Debitmemos,
        PathValues.V1_DEBITMEMOS_BULK: V1DebitmemosBulk,
        PathValues.V1_DEBITMEMOS_PDFSTATUS: V1DebitmemosPdfStatus,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_ID_APPLICATIONPARTS: V1DebitmemosDebitMemoIdApplicationParts,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_ID_ITEMS_DMITEMID_TAXATIONITEMS: V1DebitmemosDebitMemoIdItemsDmitemidTaxationItems,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY: V1DebitmemosDebitMemoKey,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_CANCEL: V1DebitmemosDebitMemoKeyCancel,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_COLLECT: V1DebitmemosDebitMemoKeyCollect,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_EINVOICE_GENERATE: V1DebitmemosDebitMemoKeyEinvoiceGenerate,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_EMAILS: V1DebitmemosDebitMemoKeyEmails,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_FILES: V1DebitmemosDebitMemoKeyFiles,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_ITEMS: V1DebitmemosDebitMemoKeyItems,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_ITEMS_DMITEMID: V1DebitmemosDebitMemoKeyItemsDmitemid,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_PDFS: V1DebitmemosDebitMemoKeyPdfs,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_POST: V1DebitmemosDebitMemoKeyPost,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_TAXATIONITEMS: V1DebitmemosDebitMemoKeyTaxationitems,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_UNPOST: V1DebitmemosDebitMemoKeyUnpost,
        PathValues.V1_INVOICES_INVOICE_KEY_DEBITMEMOS: V1InvoicesInvoiceKeyDebitmemos,
        PathValues.V1_EINVOICE_SERVICEPROVIDERS: V1EinvoiceServiceProviders,
        PathValues.V1_EINVOICE_SERVICEPROVIDERS_KEY: V1EinvoiceServiceProvidersKey,
        PathValues.V1_EINVOICE_BUSINESSREGIONS: V1EinvoiceBusinessRegions,
        PathValues.V1_EINVOICE_BUSINESSREGIONS_KEY: V1EinvoiceBusinessRegionsKey,
        PathValues.V1_EINVOICE_TEMPLATES: V1EinvoiceTemplates,
        PathValues.V1_EINVOICE_TEMPLATES_KEY: V1EinvoiceTemplatesKey,
        PathValues.V1_INVOICESCHEDULES: V1InvoiceSchedules,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY: V1InvoiceSchedulesScheduleKey,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY_EXECUTE: V1InvoiceSchedulesScheduleKeyExecute,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY_PAUSE: V1InvoiceSchedulesScheduleKeyPause,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY_RESUME: V1InvoiceSchedulesScheduleKeyResume,
        PathValues.V1_OBJECT_TAXATIONITEM: V1ObjectTaxationItem,
        PathValues.V1_TAXATIONITEMS_ID: V1TaxationitemsId,
        PathValues.V1_SEQUENCESETS: V1SequenceSets,
        PathValues.V1_SEQUENCESETS_ID: V1SequenceSetsId,
        PathValues.V1_OPERATIONS_BILLINGPREVIEW: V1OperationsBillingPreview,
        PathValues.V1_OPERATIONS_INVOICECOLLECT: V1OperationsInvoiceCollect,
        PathValues.V1_OPERATIONS_JOBS_JOB_ID: V1OperationsJobsJobId,
        PathValues.V1_OPERATIONS_BULKPDF: V1OperationsBulkPdf,
        PathValues.V1_OPERATIONS_BULKPDF_JOB_ID: V1OperationsBulkPdfJobId,
        PathValues.V1_BILLRUNS: V1BillRuns,
        PathValues.V1_BILLRUNS_BILL_RUN_ID: V1BillRunsBillRunId,
        PathValues.V1_BILLRUNS_BILL_RUN_ID_CANCEL: V1BillRunsBillRunIdCancel,
        PathValues.V1_BILLRUNS_BILL_RUN_ID_POST: V1BillRunsBillRunIdPost,
        PathValues.V1_BILLRUNS_BILL_RUN_KEY_EMAILS: V1BillRunsBillRunKeyEmails,
        PathValues.V1_BILLINGPREVIEWRUNS: V1BillingPreviewRuns,
        PathValues.V1_BILLINGPREVIEWRUNS_BILLING_PREVIEW_RUN_ID: V1BillingPreviewRunsBillingPreviewRunId,
        PathValues.V1_PAYMENTMETHODS: V1PaymentMethods,
        PathValues.V1_PAYMENTMETHODS_DECRYPTION: V1PaymentMethodsDecryption,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID: V1PaymentMethodsPaymentMethodId,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_VERIFY: V1PaymentMethodsPaymentMethodIdVerify,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_SCRUB: V1PaymentMethodsPaymentMethodIdScrub,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_PROFILES: V1PaymentMethodsPaymentMethodIdProfiles,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_PROFILES_PROFILENUMBER_CANCEL: V1PaymentMethodsPaymentMethodIdProfilesProfileNumberCancel,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_PROFILES_PROFILENUMBER_EXPIRE: V1PaymentMethodsPaymentMethodIdProfilesProfileNumberExpire,
        PathValues.PAYMENTMETHODS_APPLEPAY_DOMAINS: PaymentMethodsApplePayDomains,
        PathValues.PAYMENTMETHODS_APPLEPAY_DOMAINS_ID: PaymentMethodsApplePayDomainsId,
        PathValues.WEBPAYMENTS_SESSIONS: WebPaymentsSessions,
        PathValues.V1_OBJECT_PAYMENTMETHODSNAPSHOT_ID: V1ObjectPaymentMethodSnapshotId,
        PathValues.V1_OBJECT_PAYMENTMETHODTRANSACTIONLOG_ID: V1ObjectPaymentMethodTransactionLogId,
        PathValues.V1_PAYMENTMETHODUPDATERS: V1PaymentMethodUpdaters,
        PathValues.V1_PAYMENTMETHODUPDATERS_BATCHES: V1PaymentMethodUpdatersBatches,
        PathValues.V1_RSASIGNATURES: V1RsaSignatures,
        PathValues.V1_RSASIGNATURES_DECRYPT: V1RsaSignaturesDecrypt,
        PathValues.V1_HOSTEDPAGES: V1Hostedpages,
        PathValues.OPENPAYMENTMETHODTYPES: OpenPaymentMethodTypes,
        PathValues.OPENPAYMENTMETHODTYPES_PUBLISH_PAYMENT_METHOD_TYPE_NAME: OpenPaymentMethodTypesPublishPaymentMethodTypeName,
        PathValues.OPENPAYMENTMETHODTYPES_PAYMENT_METHOD_TYPE_NAME: OpenPaymentMethodTypesPaymentMethodTypeName,
        PathValues.OPENPAYMENTMETHODTYPES_PAYMENT_METHOD_TYPE_NAME_DRAFT_REVISION_NUMBER: OpenPaymentMethodTypesPaymentMethodTypeNameDraftRevisionNumber,
        PathValues.OPENPAYMENTMETHODTYPES_PAYMENT_METHOD_TYPE_NAME_PUBLISHED: OpenPaymentMethodTypesPaymentMethodTypeNamePublished,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_AUTHORIZE: V1PaymentMethodsPaymentMethodIdAuthorize,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_VOID_AUTHORIZE: V1PaymentMethodsPaymentMethodIdVoidAuthorize,
        PathValues.V1_PAYMENTGATEWAYS: V1Paymentgateways,
        PathValues.V1_GATEWAYSETTLEMENT_PAYMENTS_PAYMENTKEY_CHARGEBACK: V1GatewaySettlementPaymentsPaymentKeyChargeback,
        PathValues.V1_GATEWAYSETTLEMENT_PAYMENTS_PAYMENTKEY_REJECT: V1GatewaySettlementPaymentsPaymentKeyReject,
        PathValues.V1_GATEWAYSETTLEMENT_PAYMENTS_PAYMENTKEY_SETTLE: V1GatewaySettlementPaymentsPaymentKeySettle,
        PathValues.V1_REFUNDS_REFUNDKEY_RECONCILE: V1RefundsRefundKeyReconcile,
        PathValues.V1_PAYMENTS: V1Payments,
        PathValues.V1_PAYMENTS_PAYMENT_ID: V1PaymentsPaymentId,
        PathValues.V1_PAYMENTS_PAYMENT_KEY: V1PaymentsPaymentKey,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_APPLY: V1PaymentsPaymentKeyApply,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_CANCEL: V1PaymentsPaymentKeyCancel,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS: V1PaymentsPaymentKeyParts,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS_PARTID: V1PaymentsPaymentKeyPartsPartid,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS_PARTID_ITEMPARTS: V1PaymentsPaymentKeyPartsPartidItemparts,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS_PARTID_ITEMPARTS_ITEMPARTID: V1PaymentsPaymentKeyPartsPartidItempartsItempartid,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_REFUNDS: V1PaymentsPaymentKeyRefunds,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_REFUNDS_UNAPPLY: V1PaymentsPaymentKeyRefundsUnapply,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_TRANSFER: V1PaymentsPaymentKeyTransfer,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_UNAPPLY: V1PaymentsPaymentKeyUnapply,
        PathValues.V1_OBJECT_PAYMENTTRANSACTIONLOG_ID: V1ObjectPaymentTransactionLogId,
        PathValues.V1_PAYMENTRUNS: V1PaymentRuns,
        PathValues.V1_PAYMENTRUNS_PAYMENT_RUN_KEY: V1PaymentRunsPaymentRunKey,
        PathValues.V1_PAYMENTRUNS_PAYMENT_RUN_KEY_DATA: V1PaymentRunsPaymentRunKeyData,
        PathValues.V1_PAYMENTRUNS_PAYMENT_RUN_KEY_SUMMARY: V1PaymentRunsPaymentRunKeySummary,
        PathValues.V1_PAYMENTSCHEDULEITEMS_RETRYPAYMENT: V1PaymentScheduleItemsRetryPayment,
        PathValues.V1_PAYMENTSCHEDULEITEMS_ITEMID: V1PaymentScheduleItemsItemId,
        PathValues.V1_PAYMENTSCHEDULEITEMS_ITEMID_CANCEL: V1PaymentScheduleItemsItemIdCancel,
        PathValues.V1_PAYMENTSCHEDULEITEMS_ITEMID_SKIP: V1PaymentScheduleItemsItemIdSkip,
        PathValues.V1_PAYMENTSCHEDULES: V1PaymentSchedules,
        PathValues.V1_PAYMENTSCHEDULES_BATCH: V1PaymentSchedulesBatch,
        PathValues.V1_PAYMENTSCHEDULES_STATISTICS_YYYYMMDD: V1PaymentSchedulesStatisticsYyyyMmDd,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY: V1PaymentSchedulesPaymentScheduleKey,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY_CANCEL: V1PaymentSchedulesPaymentScheduleKeyCancel,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY_ITEMS: V1PaymentSchedulesPaymentScheduleKeyItems,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY_PREVIEW: V1PaymentSchedulesPaymentScheduleKeyPreview,
        PathValues.V1_REFUNDS: V1Refunds,
        PathValues.V1_REFUNDS_REFUND_ID: V1RefundsRefundId,
        PathValues.V1_REFUNDS_REFUND_KEY: V1RefundsRefundKey,
        PathValues.V1_REFUNDS_REFUND_KEY_CANCEL: V1RefundsRefundKeyCancel,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS: V1RefundsRefundKeyParts,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS_REFUNDPARTID: V1RefundsRefundKeyPartsRefundpartid,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS_REFUNDPARTID_ITEMPARTS: V1RefundsRefundKeyPartsRefundpartidItemparts,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS_REFUNDPARTID_ITEMPARTS_ITEMPARTID: V1RefundsRefundKeyPartsRefundpartidItempartsItempartid,
        PathValues.V1_ACCOUNTINGCODES: V1AccountingCodes,
        PathValues.V1_ACCOUNTINGCODES_ACID: V1AccountingCodesAcId,
        PathValues.V1_ACCOUNTINGCODES_ACID_ACTIVATE: V1AccountingCodesAcIdActivate,
        PathValues.V1_ACCOUNTINGCODES_ACID_DEACTIVATE: V1AccountingCodesAcIdDeactivate,
        PathValues.V1_ACCOUNTINGPERIODS: V1AccountingPeriods,
        PathValues.V1_ACCOUNTINGPERIODS_APID: V1AccountingPeriodsApId,
        PathValues.V1_ACCOUNTINGPERIODS_APID_CLOSE: V1AccountingPeriodsApIdClose,
        PathValues.V1_ACCOUNTINGPERIODS_APID_PENDINGCLOSE: V1AccountingPeriodsApIdPendingClose,
        PathValues.V1_ACCOUNTINGPERIODS_APID_REOPEN: V1AccountingPeriodsApIdReopen,
        PathValues.V1_ACCOUNTINGPERIODS_APID_RUNTRIALBALANCE: V1AccountingPeriodsApIdRunTrialBalance,
        PathValues.V1_JOURNALENTRIES: V1JournalEntries,
        PathValues.V1_JOURNALENTRIES_JOURNALRUNS_JRNUMBER: V1JournalEntriesJournalRunsJrNumber,
        PathValues.V1_JOURNALENTRIES_JENUMBER: V1JournalEntriesJeNumber,
        PathValues.V1_JOURNALENTRIES_JENUMBER_BASICINFORMATION: V1JournalEntriesJeNumberBasicInformation,
        PathValues.V1_JOURNALENTRIES_JENUMBER_CANCEL: V1JournalEntriesJeNumberCancel,
        PathValues.V1_JOURNALRUNS: V1JournalRuns,
        PathValues.V1_JOURNALRUNS_JRNUMBER: V1JournalRunsJrNumber,
        PathValues.V1_JOURNALRUNS_JRNUMBER_CANCEL: V1JournalRunsJrNumberCancel,
        PathValues.V1_BULK: V1Bulk,
        PathValues.V1_BULK_BULKKEY: V1BulkBulkKey,
        PathValues.V1_BULK_BULKKEY_STOP: V1BulkBulkKeyStop,
        PathValues.EVENTS_EVENTTRIGGERS: EventsEventTriggers,
        PathValues.EVENTS_EVENTTRIGGERS_ID: EventsEventTriggersId,
        PathValues.EVENTS_SCHEDULEDEVENTS: EventsScheduledEvents,
        PathValues.EVENTS_SCHEDULEDEVENTS_ID: EventsScheduledEventsId,
        PathValues.NOTIFICATIONS_NOTIFICATIONDEFINITIONS: NotificationsNotificationDefinitions,
        PathValues.NOTIFICATIONS_NOTIFICATIONDEFINITIONS_ID: NotificationsNotificationDefinitionsId,
        PathValues.NOTIFICATIONS_EMAILTEMPLATES_IMPORT: NotificationsEmailTemplatesImport,
        PathValues.NOTIFICATIONS_EMAILTEMPLATES: NotificationsEmailTemplates,
        PathValues.NOTIFICATIONS_EMAILTEMPLATES_ID: NotificationsEmailTemplatesId,
        PathValues.NOTIFICATIONS_HISTORY: NotificationsHistory,
        PathValues.NOTIFICATIONS_HISTORY_TASKS_ID: NotificationsHistoryTasksId,
        PathValues.NOTIFICATIONS_CALLOUTHISTORIES_RESEND: NotificationsCalloutHistoriesResend,
        PathValues.NOTIFICATIONS_EMAILHISTORIES_RESEND: NotificationsEmailHistoriesResend,
        PathValues.V1_NOTIFICATIONHISTORY_CALLOUT: V1NotificationHistoryCallout,
        PathValues.V1_NOTIFICATIONHISTORY_EMAIL: V1NotificationHistoryEmail,
        PathValues.OBJECTS_DEFINITIONS_DEFAULT: ObjectsDefinitionsDefault,
        PathValues.OBJECTS_MIGRATIONS: ObjectsMigrations,
        PathValues.OBJECTS_DEFINITIONS_DEFAULT_OBJECT: ObjectsDefinitionsDefaultObject,
        PathValues.OBJECTS_RECORDS_DEFAULT_OBJECT: ObjectsRecordsDefaultObject,
        PathValues.OBJECTS_RECORDS_DEFAULT_OBJECT_ID: ObjectsRecordsDefaultObjectId,
        PathValues.OBJECTS_BATCH_DEFAULT_OBJECT: ObjectsBatchDefaultObject,
        PathValues.OBJECTS_JOBS: ObjectsJobs,
        PathValues.OBJECTS_JOBS_ID: ObjectsJobsId,
        PathValues.OBJECTS_JOBS_ID_FILES: ObjectsJobsIdFiles,
        PathValues.OBJECTS_JOBS_ID_ERRORS: ObjectsJobsIdErrors,
        PathValues.OBJECTS_JOBS_ID_CANCEL: ObjectsJobsIdCancel,
        PathValues.SYSTEMHEALTH_APIREQUESTS_VOLUMESUMMARY: SystemHealthApiRequestsVolumeSummary,
        PathValues.SYSTEMHEALTH_BILLINGDOCUMENTS_VOLUMESUMMARY: SystemHealthBillingDocumentsVolumeSummary,
        PathValues.SYSTEMHEALTH_PAYMENTS_VOLUMESUMMARY: SystemHealthPaymentsVolumeSummary,
        PathValues.VERSIONS_VERSION_ID: VersionsVersionId,
        PathValues.WORKFLOWS: Workflows,
        PathValues.WORKFLOWS_IMPORT: WorkflowsImport,
        PathValues.WORKFLOWS_METRICS_JSON: WorkflowsMetricsJson,
        PathValues.WORKFLOWS_TASKS: WorkflowsTasks,
        PathValues.WORKFLOWS_TASKS_BATCH_UPDATE: WorkflowsTasksBatchUpdate,
        PathValues.WORKFLOWS_TASKS_TASK_ID: WorkflowsTasksTaskId,
        PathValues.WORKFLOWS_TASKS_TASK_ID_RERUN: WorkflowsTasksTaskIdRerun,
        PathValues.WORKFLOWS_WORKFLOW_RUNS_WORKFLOW_RUN_ID: WorkflowsWorkflowRunsWorkflowRunId,
        PathValues.WORKFLOWS_WORKFLOW_ID: WorkflowsWorkflowId,
        PathValues.WORKFLOWS_WORKFLOW_ID_EXPORT: WorkflowsWorkflowIdExport,
        PathValues.WORKFLOWS_WORKFLOW_ID_RUN: WorkflowsWorkflowIdRun,
        PathValues.WORKFLOWS_WORKFLOW_ID_VERSIONS: WorkflowsWorkflowIdVersions,
        PathValues.WORKFLOWS_WORKFLOW_ID_VERSIONS_IMPORT: WorkflowsWorkflowIdVersionsImport,
        PathValues.WORKFLOWS_WORKFLOW_RUNS_WORKFLOW_RUN_ID_STOP: WorkflowsWorkflowRunsWorkflowRunIdStop,
        PathValues.QUERY_JOBS: QueryJobs,
        PathValues.QUERY_JOBS_JOBID: QueryJobsJobId,
        PathValues.V1_BATCHQUERY_JOBS_PARTNER_PARTNER_PROJECT_PROJECT: V1BatchQueryJobsPartnerPartnerProjectProject,
        PathValues.V1_BATCHQUERY_JOBS_JOBID: V1BatchQueryJobsJobid,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS: DeploymentManagerDeploymentArtifacts,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS_COMPARE: DeploymentManagerDeploymentArtifactsCompare,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS_DEPLOY: DeploymentManagerDeploymentArtifactsDeploy,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS_RETRIEVESETTINGS: DeploymentManagerDeploymentArtifactsRetrieveSettings,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_TEMPLATES: DeploymentManagerDeploymentTemplates,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_TEMPLATES_ID: DeploymentManagerDeploymentTemplatesId,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TENANTS: DeploymentManagerDeploymentsTenants,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TEMPLATES: DeploymentManagerDeploymentsTemplates,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_MIGRATION_ID_REVERT: DeploymentManagerDeploymentsMigrationIdRevert,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_MIGRATION_ID: DeploymentManagerDeploymentsMigrationId,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TENANT_PRODUCT_CATALOG: DeploymentManagerDeploymentsTenantProductCatalog,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TEMPLATE_PRODUCT_CATALOG: DeploymentManagerDeploymentsTemplateProductCatalog,
        PathValues.V1_MULTIORGANIZATIONS_DATALABELINGJOB: V1MultiOrganizationsDataLabelingJob,
        PathValues.V1_MULTIORGANIZATIONS_DATALABELINGJOB_JOBID: V1MultiOrganizationsDataLabelingJobJobId,
        PathValues.V1_UNOREGENERATE_BOOKINGTRANSACTION: V1UnoRegenerateBookingTransaction,
        PathValues.V1_UNOREGENERATE_BILLINGTRANSACTION: V1UnoRegenerateBillingTransaction,
        PathValues.V1_UNOREGENERATE_REVRECEVENTS: V1UnoRegenerateRevRecEvents,
        PathValues.V1_UNOREGENERATE_REVRECEVENTS_DAILYCONSUMPTION: V1UnoRegenerateRevRecEventsDailyConsumption,
        PathValues.V1_UNO_DATABACKFILL_BOOKINGDATE_JOBS: V1UnoDataBackfillBookingdateJobs,
        PathValues.V1_UNO_DATABACKFILL_BOOKINGDATE_JOBS_JOB_ID: V1UnoDataBackfillBookingdateJobsJobId,
        PathValues.V1_UNO_DATABACKFILL_JOBS: V1UnoDataBackfillJobs,
        PathValues.V1_UNO_DATABACKFILL_JOBS_JOB_ID: V1UnoDataBackfillJobsJobId,
        PathValues.V1_UNO_DATABACKFILL_LISTJOBS: V1UnoDataBackfillListjobs,
        PathValues.V1_UNO_BACKFILL_JOBS_TYPE_TEMPLATE: V1UnoBackFillJobsTypeTemplate,
        PathValues.V1_ACTION_CREATE: V1ActionCreate,
        PathValues.V1_ACTION_DELETE: V1ActionDelete,
        PathValues.V1_ACTION_QUERY: V1ActionQuery,
        PathValues.V1_ACTION_QUERY_MORE: V1ActionQueryMore,
        PathValues.V1_ACTION_UPDATE: V1ActionUpdate,
        PathValues.SETTINGS_BATCHREQUESTS: SettingsBatchRequests,
        PathValues.SETTINGS_LISTING: SettingsListing,
        PathValues.V1_FILES_FILEID: V1FilesFileId,
        PathValues.V1_OBJECT_IMPORT: V1ObjectImport,
        PathValues.V1_OBJECT_IMPORT_ID: V1ObjectImportId,
        PathValues.V1_CUSTOMEXCHANGERATES_CURRENCY: V1CustomExchangeRatesCurrency,
        PathValues.V1_ATTACHMENTS: V1Attachments,
        PathValues.V1_ATTACHMENTS_ATTACHMENTID: V1AttachmentsAttachmentId,
        PathValues.V1_ATTACHMENTS_OBJECTTYPE_OBJECTKEY: V1AttachmentsObjectTypeObjectKey,
        PathValues.V1_DESCRIBE_OBJECT: V1DescribeObject,
        PathValues.V1_BATCHQUERY: V1BatchQuery,
    }
)

path_to_api = PathToApi(
    {
        PathValues.OAUTH_TOKEN: OauthToken,
        PathValues.V1_OBJECT_PRODUCT: V1ObjectProduct,
        PathValues.V1_OBJECT_PRODUCT_ID: V1ObjectProductId,
        PathValues.V1_CATALOG_PRODUCTS: V1CatalogProducts,
        PathValues.V1_CATALOG_PRODUCTS_PRODUCTKEY: V1CatalogProductsProductKey,
        PathValues.V1_CATALOGGROUPS: V1CatalogGroups,
        PathValues.V1_CATALOGGROUPS_CATALOGGROUPKEY: V1CatalogGroupsCatalogGroupKey,
        PathValues.V1_PRODUCTS_PRODUCTKEY_PRODUCTRATEPLANS: V1ProductsProductKeyProductRatePlans,
        PathValues.V1_PRODUCTRATEPLANS_ID: V1ProductRatePlansId,
        PathValues.V1_PRODUCTRATEPLANS_EXTERNALID_ID: V1ProductRatePlansExternalIdId,
        PathValues.V1_OBJECT_PRODUCTRATEPLAN: V1ObjectProductRatePlan,
        PathValues.V1_OBJECT_PRODUCTRATEPLAN_ID: V1ObjectProductRatePlanId,
        PathValues.V1_PRODUCTRATEPLANDEFINITIONS: V1ProductRateplanDefinitions,
        PathValues.V1_PRODUCTRATEPLANDEFINITIONS_PRODUCTRATEPLANDEFINITIONKEY: V1ProductRateplanDefinitionsProductRateplanDefinitionKey,
        PathValues.V1_PRODUCTRATEPLANCHARGES_PRODUCTRATEPLANCHARGEKEY: V1ProductRatePlanChargesProductRatePlanChargeKey,
        PathValues.V1_OBJECT_PRODUCTRATEPLANCHARGE: V1ObjectProductRatePlanCharge,
        PathValues.V1_OBJECT_PRODUCTRATEPLANCHARGE_ID: V1ObjectProductRatePlanChargeId,
        PathValues.V1_PRODUCTCHARGEDEFINITIONS: V1ProductChargeDefinitions,
        PathValues.V1_PRODUCTCHARGEDEFINITIONS_BULK: V1ProductChargeDefinitionsBulk,
        PathValues.V1_PRODUCTCHARGEDEFINITIONS_PRODUCTCHARGEDEFINITIONKEY: V1ProductChargeDefinitionsProductChargeDefinitionKey,
        PathValues.V1_OBJECT_PRODUCTRATEPLANCHARGETIER_ID: V1ObjectProductRatePlanChargeTierId,
        PathValues.V1_REVPROACCOUNTINGCODES: V1RevproAccountingCodes,
        PathValues.V1_ACCOUNTS: V1Accounts,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY: V1AccountsAccountKey,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY_PAYMENTMETHODS: V1AccountsAccountKeyPaymentMethods,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY_PAYMENTMETHODS_DEFAULT: V1AccountsAccountKeyPaymentMethodsDefault,
        PathValues.V1_ACCOUNTS_ACCOUNTKEY_SUMMARY: V1AccountsAccountKeySummary,
        PathValues.V1_CONTACTS: V1Contacts,
        PathValues.V1_CONTACTS_CONTACT_ID: V1ContactsContactId,
        PathValues.V1_CONTACTS_CONTACT_ID_SCRUB: V1ContactsContactIdScrub,
        PathValues.V1_CONTACTSNAPSHOTS_CONTACTSNAPSHOTID: V1ContactSnapshotsContactSnapshotId,
        PathValues.V1_SIGNUP: V1SignUp,
        PathValues.V1_ORDERS_PREVIEW: V1OrdersPreview,
        PathValues.V1_ASYNC_ORDERS_PREVIEW: V1AsyncOrdersPreview,
        PathValues.V1_ORDERS: V1Orders,
        PathValues.V1_ASYNC_ORDERS: V1AsyncOrders,
        PathValues.V1_ORDERS_ORDER_NUMBER: V1OrdersOrderNumber,
        PathValues.V1_ASYNCJOBS_JOB_ID: V1AsyncJobsJobId,
        PathValues.V1_ORDERS_SUBSCRIPTION_OWNER_ACCOUNT_NUMBER: V1OrdersSubscriptionOwnerAccountNumber,
        PathValues.V1_ORDERS_SUBSCRIPTION_SUBSCRIPTION_NUMBER: V1OrdersSubscriptionSubscriptionNumber,
        PathValues.V1_ORDERS_INVOICE_OWNER_ACCOUNT_NUMBER: V1OrdersInvoiceOwnerAccountNumber,
        PathValues.V1_ORDERS_ORDER_NUMBER_CUSTOM_FIELDS: V1OrdersOrderNumberCustomFields,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_NUMBER_CUSTOM_FIELDS: V1SubscriptionsSubscriptionNumberCustomFields,
        PathValues.V1_ORDERS_ORDER_NUMBER_TRIGGER_DATES: V1OrdersOrderNumberTriggerDates,
        PathValues.V1_ORDERS_ORDER_NUMBER_ACTIVATE: V1OrdersOrderNumberActivate,
        PathValues.V1_ORDERS_ORDER_NUMBER_CANCEL: V1OrdersOrderNumberCancel,
        PathValues.V1_ORDERS_SUBSCRIPTION_SUBSCRIPTIONKEY_PENDING: V1OrdersSubscriptionSubscriptionKeyPending,
        PathValues.V1_ORDER_ACTIONS_ID: V1OrderActionsId,
        PathValues.V1_ORDERLINEITEMS_ITEM_ID: V1OrderLineItemsItemId,
        PathValues.V1_ORDERLINEITEMS_BULK: V1OrderLineItemsBulk,
        PathValues.V1_FULFILLMENTS: V1Fulfillments,
        PathValues.V1_FULFILLMENTS_KEY: V1FulfillmentsKey,
        PathValues.V1_FULFILLMENTITEMS: V1FulfillmentItems,
        PathValues.V1_FULFILLMENTITEMS_ID: V1FulfillmentItemsId,
        PathValues.V1_RAMPS_RAMP_NUMBER: V1RampsRampNumber,
        PathValues.V1_RAMPS_RAMP_NUMBER_RAMPMETRICS: V1RampsRampNumberRampMetrics,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_KEY_RAMPS: V1SubscriptionsSubscriptionKeyRamps,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_KEY_RAMPMETRICS: V1SubscriptionsSubscriptionKeyRampMetrics,
        PathValues.V1_ORDERS_ORDER_NUMBER_RAMPMETRICS: V1OrdersOrderNumberRampMetrics,
        PathValues.V1_SUBSCRIPTIONS_PREVIEW: V1SubscriptionsPreview,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_PREVIEW: V1SubscriptionsSubscriptionKeyPreview,
        PathValues.V1_SUBSCRIPTIONS: V1Subscriptions,
        PathValues.V1_SUBSCRIPTIONS_ACCOUNTS_ACCOUNTKEY: V1SubscriptionsAccountsAccountKey,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY: V1SubscriptionsSubscriptionKey,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_VERSIONS_VERSION: V1SubscriptionsSubscriptionKeyVersionsVersion,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_RENEW: V1SubscriptionsSubscriptionKeyRenew,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_CANCEL: V1SubscriptionsSubscriptionKeyCancel,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_RESUME: V1SubscriptionsSubscriptionKeyResume,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_SUSPEND: V1SubscriptionsSubscriptionKeySuspend,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTIONKEY_DELETE: V1SubscriptionsSubscriptionKeyDelete,
        PathValues.V1_SUBSCRIPTIONS_SUBSCRIPTION_NUMBER_VERSIONS_VERSION_CUSTOM_FIELDS: V1SubscriptionsSubscriptionNumberVersionsVersionCustomFields,
        PathValues.V1_RATEPLANS_RATE_PLAN_ID: V1RateplansRatePlanId,
        PathValues.V1_PPDD_REVERSEROLLOVER: V1PpddReverseRollover,
        PathValues.V1_PPDD_ROLLOVER: V1PpddRollover,
        PathValues.V1_PREPAIDBALANCEFUNDS_DEPLETE: V1PrepaidBalanceFundsDeplete,
        PathValues.V1_USAGE: V1Usage,
        PathValues.V1_USAGE_ACCOUNTS_ACCOUNTKEY: V1UsageAccountsAccountKey,
        PathValues.V1_INVOICES_INVOICEITEM_INVOICEITEMID_USAGERATEDETAIL: V1InvoicesInvoiceItemInvoiceItemIdUsageRateDetail,
        PathValues.V1_OBJECT_USAGE: V1ObjectUsage,
        PathValues.V1_OBJECT_USAGE_ID: V1ObjectUsageId,
        PathValues.V1_ADJUSTMENTS: V1Adjustments,
        PathValues.V1_ADJUSTMENTS_PREVIEW: V1AdjustmentsPreview,
        PathValues.V1_ADJUSTMENTS_ADJUSTMENTKEY: V1AdjustmentsAdjustmentKey,
        PathValues.V1_ADJUSTMENTS_ADJUSTMENT_ID_CANCEL: V1AdjustmentsAdjustmentIdCancel,
        PathValues.V1_BILLINGDOCUMENTS: V1BillingDocuments,
        PathValues.V1_ACCOUNTS_BILLINGDOCUMENTS_FILES_DELETIONJOBS: V1AccountsBillingDocumentsFilesDeletionJobs,
        PathValues.V1_ACCOUNTS_BILLINGDOCUMENTS_FILES_DELETIONJOBS_JOB_ID: V1AccountsBillingDocumentsFilesDeletionJobsJobId,
        PathValues.V1_ACCOUNTS_KEY_BILLINGDOCUMENTS_GENERATE: V1AccountsKeyBillingDocumentsGenerate,
        PathValues.V1_INVOICES: V1Invoices,
        PathValues.V1_INVOICES_BATCH: V1InvoicesBatch,
        PathValues.V1_INVOICES_BULKPOST: V1InvoicesBulkPost,
        PathValues.V1_INVOICES_PDFSTATUS: V1InvoicesPdfStatus,
        PathValues.V1_INVOICES_INVOICE_KEY: V1InvoicesInvoiceKey,
        PathValues.V1_INVOICES_INVOICE_KEY_APPLICATIONPARTS: V1InvoicesInvoiceKeyApplicationParts,
        PathValues.V1_INVOICES_INVOICE_KEY_EINVOICE_GENERATE: V1InvoicesInvoiceKeyEinvoiceGenerate,
        PathValues.V1_INVOICES_INVOICE_KEY_EMAILS: V1InvoicesInvoiceKeyEmails,
        PathValues.V1_INVOICES_INVOICE_KEY_FILES: V1InvoicesInvoiceKeyFiles,
        PathValues.V1_INVOICES_INVOICE_KEY_ITEMS: V1InvoicesInvoiceKeyItems,
        PathValues.V1_INVOICES_INVOICE_KEY_ITEMS_ITEM_ID_TAXATIONITEMS: V1InvoicesInvoiceKeyItemsItemIdTaxationItems,
        PathValues.V1_INVOICES_INVOICE_KEY_REVERSE: V1InvoicesInvoiceKeyReverse,
        PathValues.V1_INVOICES_INVOICE_KEY_TAXATIONITEMS: V1InvoicesInvoiceKeyTaxationitems,
        PathValues.V1_INVOICES_INVOICE_KEY_WRITEOFF: V1InvoicesInvoiceKeyWriteOff,
        PathValues.V1_CREDITMEMOS: V1Creditmemos,
        PathValues.V1_CREDITMEMOS_BULK: V1CreditmemosBulk,
        PathValues.V1_CREDITMEMOS_PDFSTATUS: V1CreditmemosPdfStatus,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_ID_ITEMS_CMITEMID_TAXATIONITEMS: V1CreditmemosCreditMemoIdItemsCmitemidTaxationItems,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_ID_WRITEOFF: V1CreditmemosCreditMemoIdWriteOff,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY: V1CreditmemosCreditMemoKey,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_APPLY: V1CreditmemosCreditMemoKeyApply,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_CANCEL: V1CreditmemosCreditMemoKeyCancel,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_EINVOICE_GENERATE: V1CreditmemosCreditMemoKeyEinvoiceGenerate,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_EMAILS: V1CreditmemosCreditMemoKeyEmails,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_FILES: V1CreditmemosCreditMemoKeyFiles,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_ITEMS: V1CreditmemosCreditMemoKeyItems,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_ITEMS_CMITEMID: V1CreditmemosCreditMemoKeyItemsCmitemid,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_PARTS: V1CreditmemosCreditMemoKeyParts,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_PARTS_PARTID: V1CreditmemosCreditMemoKeyPartsPartid,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_PDFS: V1CreditmemosCreditMemoKeyPdfs,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_POST: V1CreditmemosCreditMemoKeyPost,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_REFUNDS: V1CreditmemosCreditMemoKeyRefunds,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_REVERSE: V1CreditmemosCreditMemoKeyReverse,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_TAXATIONITEMS: V1CreditmemosCreditMemoKeyTaxationitems,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_UNAPPLY: V1CreditmemosCreditMemoKeyUnapply,
        PathValues.V1_CREDITMEMOS_CREDIT_MEMO_KEY_UNPOST: V1CreditmemosCreditMemoKeyUnpost,
        PathValues.V1_INVOICES_INVOICE_KEY_CREDITMEMOS: V1InvoicesInvoiceKeyCreditmemos,
        PathValues.V1_DEBITMEMOS: V1Debitmemos,
        PathValues.V1_DEBITMEMOS_BULK: V1DebitmemosBulk,
        PathValues.V1_DEBITMEMOS_PDFSTATUS: V1DebitmemosPdfStatus,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_ID_APPLICATIONPARTS: V1DebitmemosDebitMemoIdApplicationParts,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_ID_ITEMS_DMITEMID_TAXATIONITEMS: V1DebitmemosDebitMemoIdItemsDmitemidTaxationItems,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY: V1DebitmemosDebitMemoKey,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_CANCEL: V1DebitmemosDebitMemoKeyCancel,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_COLLECT: V1DebitmemosDebitMemoKeyCollect,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_EINVOICE_GENERATE: V1DebitmemosDebitMemoKeyEinvoiceGenerate,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_EMAILS: V1DebitmemosDebitMemoKeyEmails,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_FILES: V1DebitmemosDebitMemoKeyFiles,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_ITEMS: V1DebitmemosDebitMemoKeyItems,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_ITEMS_DMITEMID: V1DebitmemosDebitMemoKeyItemsDmitemid,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_PDFS: V1DebitmemosDebitMemoKeyPdfs,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_POST: V1DebitmemosDebitMemoKeyPost,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_TAXATIONITEMS: V1DebitmemosDebitMemoKeyTaxationitems,
        PathValues.V1_DEBITMEMOS_DEBIT_MEMO_KEY_UNPOST: V1DebitmemosDebitMemoKeyUnpost,
        PathValues.V1_INVOICES_INVOICE_KEY_DEBITMEMOS: V1InvoicesInvoiceKeyDebitmemos,
        PathValues.V1_EINVOICE_SERVICEPROVIDERS: V1EinvoiceServiceProviders,
        PathValues.V1_EINVOICE_SERVICEPROVIDERS_KEY: V1EinvoiceServiceProvidersKey,
        PathValues.V1_EINVOICE_BUSINESSREGIONS: V1EinvoiceBusinessRegions,
        PathValues.V1_EINVOICE_BUSINESSREGIONS_KEY: V1EinvoiceBusinessRegionsKey,
        PathValues.V1_EINVOICE_TEMPLATES: V1EinvoiceTemplates,
        PathValues.V1_EINVOICE_TEMPLATES_KEY: V1EinvoiceTemplatesKey,
        PathValues.V1_INVOICESCHEDULES: V1InvoiceSchedules,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY: V1InvoiceSchedulesScheduleKey,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY_EXECUTE: V1InvoiceSchedulesScheduleKeyExecute,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY_PAUSE: V1InvoiceSchedulesScheduleKeyPause,
        PathValues.V1_INVOICESCHEDULES_SCHEDULE_KEY_RESUME: V1InvoiceSchedulesScheduleKeyResume,
        PathValues.V1_OBJECT_TAXATIONITEM: V1ObjectTaxationItem,
        PathValues.V1_TAXATIONITEMS_ID: V1TaxationitemsId,
        PathValues.V1_SEQUENCESETS: V1SequenceSets,
        PathValues.V1_SEQUENCESETS_ID: V1SequenceSetsId,
        PathValues.V1_OPERATIONS_BILLINGPREVIEW: V1OperationsBillingPreview,
        PathValues.V1_OPERATIONS_INVOICECOLLECT: V1OperationsInvoiceCollect,
        PathValues.V1_OPERATIONS_JOBS_JOB_ID: V1OperationsJobsJobId,
        PathValues.V1_OPERATIONS_BULKPDF: V1OperationsBulkPdf,
        PathValues.V1_OPERATIONS_BULKPDF_JOB_ID: V1OperationsBulkPdfJobId,
        PathValues.V1_BILLRUNS: V1BillRuns,
        PathValues.V1_BILLRUNS_BILL_RUN_ID: V1BillRunsBillRunId,
        PathValues.V1_BILLRUNS_BILL_RUN_ID_CANCEL: V1BillRunsBillRunIdCancel,
        PathValues.V1_BILLRUNS_BILL_RUN_ID_POST: V1BillRunsBillRunIdPost,
        PathValues.V1_BILLRUNS_BILL_RUN_KEY_EMAILS: V1BillRunsBillRunKeyEmails,
        PathValues.V1_BILLINGPREVIEWRUNS: V1BillingPreviewRuns,
        PathValues.V1_BILLINGPREVIEWRUNS_BILLING_PREVIEW_RUN_ID: V1BillingPreviewRunsBillingPreviewRunId,
        PathValues.V1_PAYMENTMETHODS: V1PaymentMethods,
        PathValues.V1_PAYMENTMETHODS_DECRYPTION: V1PaymentMethodsDecryption,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID: V1PaymentMethodsPaymentMethodId,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_VERIFY: V1PaymentMethodsPaymentMethodIdVerify,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_SCRUB: V1PaymentMethodsPaymentMethodIdScrub,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_PROFILES: V1PaymentMethodsPaymentMethodIdProfiles,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_PROFILES_PROFILENUMBER_CANCEL: V1PaymentMethodsPaymentMethodIdProfilesProfileNumberCancel,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_PROFILES_PROFILENUMBER_EXPIRE: V1PaymentMethodsPaymentMethodIdProfilesProfileNumberExpire,
        PathValues.PAYMENTMETHODS_APPLEPAY_DOMAINS: PaymentMethodsApplePayDomains,
        PathValues.PAYMENTMETHODS_APPLEPAY_DOMAINS_ID: PaymentMethodsApplePayDomainsId,
        PathValues.WEBPAYMENTS_SESSIONS: WebPaymentsSessions,
        PathValues.V1_OBJECT_PAYMENTMETHODSNAPSHOT_ID: V1ObjectPaymentMethodSnapshotId,
        PathValues.V1_OBJECT_PAYMENTMETHODTRANSACTIONLOG_ID: V1ObjectPaymentMethodTransactionLogId,
        PathValues.V1_PAYMENTMETHODUPDATERS: V1PaymentMethodUpdaters,
        PathValues.V1_PAYMENTMETHODUPDATERS_BATCHES: V1PaymentMethodUpdatersBatches,
        PathValues.V1_RSASIGNATURES: V1RsaSignatures,
        PathValues.V1_RSASIGNATURES_DECRYPT: V1RsaSignaturesDecrypt,
        PathValues.V1_HOSTEDPAGES: V1Hostedpages,
        PathValues.OPENPAYMENTMETHODTYPES: OpenPaymentMethodTypes,
        PathValues.OPENPAYMENTMETHODTYPES_PUBLISH_PAYMENT_METHOD_TYPE_NAME: OpenPaymentMethodTypesPublishPaymentMethodTypeName,
        PathValues.OPENPAYMENTMETHODTYPES_PAYMENT_METHOD_TYPE_NAME: OpenPaymentMethodTypesPaymentMethodTypeName,
        PathValues.OPENPAYMENTMETHODTYPES_PAYMENT_METHOD_TYPE_NAME_DRAFT_REVISION_NUMBER: OpenPaymentMethodTypesPaymentMethodTypeNameDraftRevisionNumber,
        PathValues.OPENPAYMENTMETHODTYPES_PAYMENT_METHOD_TYPE_NAME_PUBLISHED: OpenPaymentMethodTypesPaymentMethodTypeNamePublished,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_AUTHORIZE: V1PaymentMethodsPaymentMethodIdAuthorize,
        PathValues.V1_PAYMENTMETHODS_PAYMENTMETHODID_VOID_AUTHORIZE: V1PaymentMethodsPaymentMethodIdVoidAuthorize,
        PathValues.V1_PAYMENTGATEWAYS: V1Paymentgateways,
        PathValues.V1_GATEWAYSETTLEMENT_PAYMENTS_PAYMENTKEY_CHARGEBACK: V1GatewaySettlementPaymentsPaymentKeyChargeback,
        PathValues.V1_GATEWAYSETTLEMENT_PAYMENTS_PAYMENTKEY_REJECT: V1GatewaySettlementPaymentsPaymentKeyReject,
        PathValues.V1_GATEWAYSETTLEMENT_PAYMENTS_PAYMENTKEY_SETTLE: V1GatewaySettlementPaymentsPaymentKeySettle,
        PathValues.V1_REFUNDS_REFUNDKEY_RECONCILE: V1RefundsRefundKeyReconcile,
        PathValues.V1_PAYMENTS: V1Payments,
        PathValues.V1_PAYMENTS_PAYMENT_ID: V1PaymentsPaymentId,
        PathValues.V1_PAYMENTS_PAYMENT_KEY: V1PaymentsPaymentKey,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_APPLY: V1PaymentsPaymentKeyApply,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_CANCEL: V1PaymentsPaymentKeyCancel,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS: V1PaymentsPaymentKeyParts,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS_PARTID: V1PaymentsPaymentKeyPartsPartid,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS_PARTID_ITEMPARTS: V1PaymentsPaymentKeyPartsPartidItemparts,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_PARTS_PARTID_ITEMPARTS_ITEMPARTID: V1PaymentsPaymentKeyPartsPartidItempartsItempartid,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_REFUNDS: V1PaymentsPaymentKeyRefunds,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_REFUNDS_UNAPPLY: V1PaymentsPaymentKeyRefundsUnapply,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_TRANSFER: V1PaymentsPaymentKeyTransfer,
        PathValues.V1_PAYMENTS_PAYMENT_KEY_UNAPPLY: V1PaymentsPaymentKeyUnapply,
        PathValues.V1_OBJECT_PAYMENTTRANSACTIONLOG_ID: V1ObjectPaymentTransactionLogId,
        PathValues.V1_PAYMENTRUNS: V1PaymentRuns,
        PathValues.V1_PAYMENTRUNS_PAYMENT_RUN_KEY: V1PaymentRunsPaymentRunKey,
        PathValues.V1_PAYMENTRUNS_PAYMENT_RUN_KEY_DATA: V1PaymentRunsPaymentRunKeyData,
        PathValues.V1_PAYMENTRUNS_PAYMENT_RUN_KEY_SUMMARY: V1PaymentRunsPaymentRunKeySummary,
        PathValues.V1_PAYMENTSCHEDULEITEMS_RETRYPAYMENT: V1PaymentScheduleItemsRetryPayment,
        PathValues.V1_PAYMENTSCHEDULEITEMS_ITEMID: V1PaymentScheduleItemsItemId,
        PathValues.V1_PAYMENTSCHEDULEITEMS_ITEMID_CANCEL: V1PaymentScheduleItemsItemIdCancel,
        PathValues.V1_PAYMENTSCHEDULEITEMS_ITEMID_SKIP: V1PaymentScheduleItemsItemIdSkip,
        PathValues.V1_PAYMENTSCHEDULES: V1PaymentSchedules,
        PathValues.V1_PAYMENTSCHEDULES_BATCH: V1PaymentSchedulesBatch,
        PathValues.V1_PAYMENTSCHEDULES_STATISTICS_YYYYMMDD: V1PaymentSchedulesStatisticsYyyyMmDd,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY: V1PaymentSchedulesPaymentScheduleKey,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY_CANCEL: V1PaymentSchedulesPaymentScheduleKeyCancel,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY_ITEMS: V1PaymentSchedulesPaymentScheduleKeyItems,
        PathValues.V1_PAYMENTSCHEDULES_PAYMENT_SCHEDULE_KEY_PREVIEW: V1PaymentSchedulesPaymentScheduleKeyPreview,
        PathValues.V1_REFUNDS: V1Refunds,
        PathValues.V1_REFUNDS_REFUND_ID: V1RefundsRefundId,
        PathValues.V1_REFUNDS_REFUND_KEY: V1RefundsRefundKey,
        PathValues.V1_REFUNDS_REFUND_KEY_CANCEL: V1RefundsRefundKeyCancel,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS: V1RefundsRefundKeyParts,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS_REFUNDPARTID: V1RefundsRefundKeyPartsRefundpartid,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS_REFUNDPARTID_ITEMPARTS: V1RefundsRefundKeyPartsRefundpartidItemparts,
        PathValues.V1_REFUNDS_REFUND_KEY_PARTS_REFUNDPARTID_ITEMPARTS_ITEMPARTID: V1RefundsRefundKeyPartsRefundpartidItempartsItempartid,
        PathValues.V1_ACCOUNTINGCODES: V1AccountingCodes,
        PathValues.V1_ACCOUNTINGCODES_ACID: V1AccountingCodesAcId,
        PathValues.V1_ACCOUNTINGCODES_ACID_ACTIVATE: V1AccountingCodesAcIdActivate,
        PathValues.V1_ACCOUNTINGCODES_ACID_DEACTIVATE: V1AccountingCodesAcIdDeactivate,
        PathValues.V1_ACCOUNTINGPERIODS: V1AccountingPeriods,
        PathValues.V1_ACCOUNTINGPERIODS_APID: V1AccountingPeriodsApId,
        PathValues.V1_ACCOUNTINGPERIODS_APID_CLOSE: V1AccountingPeriodsApIdClose,
        PathValues.V1_ACCOUNTINGPERIODS_APID_PENDINGCLOSE: V1AccountingPeriodsApIdPendingClose,
        PathValues.V1_ACCOUNTINGPERIODS_APID_REOPEN: V1AccountingPeriodsApIdReopen,
        PathValues.V1_ACCOUNTINGPERIODS_APID_RUNTRIALBALANCE: V1AccountingPeriodsApIdRunTrialBalance,
        PathValues.V1_JOURNALENTRIES: V1JournalEntries,
        PathValues.V1_JOURNALENTRIES_JOURNALRUNS_JRNUMBER: V1JournalEntriesJournalRunsJrNumber,
        PathValues.V1_JOURNALENTRIES_JENUMBER: V1JournalEntriesJeNumber,
        PathValues.V1_JOURNALENTRIES_JENUMBER_BASICINFORMATION: V1JournalEntriesJeNumberBasicInformation,
        PathValues.V1_JOURNALENTRIES_JENUMBER_CANCEL: V1JournalEntriesJeNumberCancel,
        PathValues.V1_JOURNALRUNS: V1JournalRuns,
        PathValues.V1_JOURNALRUNS_JRNUMBER: V1JournalRunsJrNumber,
        PathValues.V1_JOURNALRUNS_JRNUMBER_CANCEL: V1JournalRunsJrNumberCancel,
        PathValues.V1_BULK: V1Bulk,
        PathValues.V1_BULK_BULKKEY: V1BulkBulkKey,
        PathValues.V1_BULK_BULKKEY_STOP: V1BulkBulkKeyStop,
        PathValues.EVENTS_EVENTTRIGGERS: EventsEventTriggers,
        PathValues.EVENTS_EVENTTRIGGERS_ID: EventsEventTriggersId,
        PathValues.EVENTS_SCHEDULEDEVENTS: EventsScheduledEvents,
        PathValues.EVENTS_SCHEDULEDEVENTS_ID: EventsScheduledEventsId,
        PathValues.NOTIFICATIONS_NOTIFICATIONDEFINITIONS: NotificationsNotificationDefinitions,
        PathValues.NOTIFICATIONS_NOTIFICATIONDEFINITIONS_ID: NotificationsNotificationDefinitionsId,
        PathValues.NOTIFICATIONS_EMAILTEMPLATES_IMPORT: NotificationsEmailTemplatesImport,
        PathValues.NOTIFICATIONS_EMAILTEMPLATES: NotificationsEmailTemplates,
        PathValues.NOTIFICATIONS_EMAILTEMPLATES_ID: NotificationsEmailTemplatesId,
        PathValues.NOTIFICATIONS_HISTORY: NotificationsHistory,
        PathValues.NOTIFICATIONS_HISTORY_TASKS_ID: NotificationsHistoryTasksId,
        PathValues.NOTIFICATIONS_CALLOUTHISTORIES_RESEND: NotificationsCalloutHistoriesResend,
        PathValues.NOTIFICATIONS_EMAILHISTORIES_RESEND: NotificationsEmailHistoriesResend,
        PathValues.V1_NOTIFICATIONHISTORY_CALLOUT: V1NotificationHistoryCallout,
        PathValues.V1_NOTIFICATIONHISTORY_EMAIL: V1NotificationHistoryEmail,
        PathValues.OBJECTS_DEFINITIONS_DEFAULT: ObjectsDefinitionsDefault,
        PathValues.OBJECTS_MIGRATIONS: ObjectsMigrations,
        PathValues.OBJECTS_DEFINITIONS_DEFAULT_OBJECT: ObjectsDefinitionsDefaultObject,
        PathValues.OBJECTS_RECORDS_DEFAULT_OBJECT: ObjectsRecordsDefaultObject,
        PathValues.OBJECTS_RECORDS_DEFAULT_OBJECT_ID: ObjectsRecordsDefaultObjectId,
        PathValues.OBJECTS_BATCH_DEFAULT_OBJECT: ObjectsBatchDefaultObject,
        PathValues.OBJECTS_JOBS: ObjectsJobs,
        PathValues.OBJECTS_JOBS_ID: ObjectsJobsId,
        PathValues.OBJECTS_JOBS_ID_FILES: ObjectsJobsIdFiles,
        PathValues.OBJECTS_JOBS_ID_ERRORS: ObjectsJobsIdErrors,
        PathValues.OBJECTS_JOBS_ID_CANCEL: ObjectsJobsIdCancel,
        PathValues.SYSTEMHEALTH_APIREQUESTS_VOLUMESUMMARY: SystemHealthApiRequestsVolumeSummary,
        PathValues.SYSTEMHEALTH_BILLINGDOCUMENTS_VOLUMESUMMARY: SystemHealthBillingDocumentsVolumeSummary,
        PathValues.SYSTEMHEALTH_PAYMENTS_VOLUMESUMMARY: SystemHealthPaymentsVolumeSummary,
        PathValues.VERSIONS_VERSION_ID: VersionsVersionId,
        PathValues.WORKFLOWS: Workflows,
        PathValues.WORKFLOWS_IMPORT: WorkflowsImport,
        PathValues.WORKFLOWS_METRICS_JSON: WorkflowsMetricsJson,
        PathValues.WORKFLOWS_TASKS: WorkflowsTasks,
        PathValues.WORKFLOWS_TASKS_BATCH_UPDATE: WorkflowsTasksBatchUpdate,
        PathValues.WORKFLOWS_TASKS_TASK_ID: WorkflowsTasksTaskId,
        PathValues.WORKFLOWS_TASKS_TASK_ID_RERUN: WorkflowsTasksTaskIdRerun,
        PathValues.WORKFLOWS_WORKFLOW_RUNS_WORKFLOW_RUN_ID: WorkflowsWorkflowRunsWorkflowRunId,
        PathValues.WORKFLOWS_WORKFLOW_ID: WorkflowsWorkflowId,
        PathValues.WORKFLOWS_WORKFLOW_ID_EXPORT: WorkflowsWorkflowIdExport,
        PathValues.WORKFLOWS_WORKFLOW_ID_RUN: WorkflowsWorkflowIdRun,
        PathValues.WORKFLOWS_WORKFLOW_ID_VERSIONS: WorkflowsWorkflowIdVersions,
        PathValues.WORKFLOWS_WORKFLOW_ID_VERSIONS_IMPORT: WorkflowsWorkflowIdVersionsImport,
        PathValues.WORKFLOWS_WORKFLOW_RUNS_WORKFLOW_RUN_ID_STOP: WorkflowsWorkflowRunsWorkflowRunIdStop,
        PathValues.QUERY_JOBS: QueryJobs,
        PathValues.QUERY_JOBS_JOBID: QueryJobsJobId,
        PathValues.V1_BATCHQUERY_JOBS_PARTNER_PARTNER_PROJECT_PROJECT: V1BatchQueryJobsPartnerPartnerProjectProject,
        PathValues.V1_BATCHQUERY_JOBS_JOBID: V1BatchQueryJobsJobid,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS: DeploymentManagerDeploymentArtifacts,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS_COMPARE: DeploymentManagerDeploymentArtifactsCompare,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS_DEPLOY: DeploymentManagerDeploymentArtifactsDeploy,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_ARTIFACTS_RETRIEVESETTINGS: DeploymentManagerDeploymentArtifactsRetrieveSettings,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_TEMPLATES: DeploymentManagerDeploymentTemplates,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENT_TEMPLATES_ID: DeploymentManagerDeploymentTemplatesId,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TENANTS: DeploymentManagerDeploymentsTenants,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TEMPLATES: DeploymentManagerDeploymentsTemplates,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_MIGRATION_ID_REVERT: DeploymentManagerDeploymentsMigrationIdRevert,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_MIGRATION_ID: DeploymentManagerDeploymentsMigrationId,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TENANT_PRODUCT_CATALOG: DeploymentManagerDeploymentsTenantProductCatalog,
        PathValues.DEPLOYMENTMANAGER_DEPLOYMENTS_TEMPLATE_PRODUCT_CATALOG: DeploymentManagerDeploymentsTemplateProductCatalog,
        PathValues.V1_MULTIORGANIZATIONS_DATALABELINGJOB: V1MultiOrganizationsDataLabelingJob,
        PathValues.V1_MULTIORGANIZATIONS_DATALABELINGJOB_JOBID: V1MultiOrganizationsDataLabelingJobJobId,
        PathValues.V1_UNOREGENERATE_BOOKINGTRANSACTION: V1UnoRegenerateBookingTransaction,
        PathValues.V1_UNOREGENERATE_BILLINGTRANSACTION: V1UnoRegenerateBillingTransaction,
        PathValues.V1_UNOREGENERATE_REVRECEVENTS: V1UnoRegenerateRevRecEvents,
        PathValues.V1_UNOREGENERATE_REVRECEVENTS_DAILYCONSUMPTION: V1UnoRegenerateRevRecEventsDailyConsumption,
        PathValues.V1_UNO_DATABACKFILL_BOOKINGDATE_JOBS: V1UnoDataBackfillBookingdateJobs,
        PathValues.V1_UNO_DATABACKFILL_BOOKINGDATE_JOBS_JOB_ID: V1UnoDataBackfillBookingdateJobsJobId,
        PathValues.V1_UNO_DATABACKFILL_JOBS: V1UnoDataBackfillJobs,
        PathValues.V1_UNO_DATABACKFILL_JOBS_JOB_ID: V1UnoDataBackfillJobsJobId,
        PathValues.V1_UNO_DATABACKFILL_LISTJOBS: V1UnoDataBackfillListjobs,
        PathValues.V1_UNO_BACKFILL_JOBS_TYPE_TEMPLATE: V1UnoBackFillJobsTypeTemplate,
        PathValues.V1_ACTION_CREATE: V1ActionCreate,
        PathValues.V1_ACTION_DELETE: V1ActionDelete,
        PathValues.V1_ACTION_QUERY: V1ActionQuery,
        PathValues.V1_ACTION_QUERY_MORE: V1ActionQueryMore,
        PathValues.V1_ACTION_UPDATE: V1ActionUpdate,
        PathValues.SETTINGS_BATCHREQUESTS: SettingsBatchRequests,
        PathValues.SETTINGS_LISTING: SettingsListing,
        PathValues.V1_FILES_FILEID: V1FilesFileId,
        PathValues.V1_OBJECT_IMPORT: V1ObjectImport,
        PathValues.V1_OBJECT_IMPORT_ID: V1ObjectImportId,
        PathValues.V1_CUSTOMEXCHANGERATES_CURRENCY: V1CustomExchangeRatesCurrency,
        PathValues.V1_ATTACHMENTS: V1Attachments,
        PathValues.V1_ATTACHMENTS_ATTACHMENTID: V1AttachmentsAttachmentId,
        PathValues.V1_ATTACHMENTS_OBJECTTYPE_OBJECTKEY: V1AttachmentsObjectTypeObjectKey,
        PathValues.V1_DESCRIBE_OBJECT: V1DescribeObject,
        PathValues.V1_BATCHQUERY: V1BatchQuery,
    }
)
