# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from zuora_python_sdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    CREDIT_MEMOS = "Credit Memos"
    DEBIT_MEMOS = "Debit Memos"
    INVOICES = "Invoices"
    ORDERS = "Orders"
    NOTIFICATIONS = "Notifications"
    WORKFLOWS = "Workflows"
    EINVOICING = "E-Invoicing"
    PAYMENT_METHODS = "Payment Methods"
    PAYMENTS = "Payments"
    PAYMENT_SCHEDULES = "Payment Schedules"
    SUBSCRIPTIONS = "Subscriptions"
    ACCOUNTING_PERIODS = "Accounting Periods"
    DATA_BACKFILL = "Data Backfill"
    REFUNDS = "Refunds"
    CONFIGURATION_TEMPLATES = "Configuration Templates"
    FULFILLMENTS = "Fulfillments"
    ACCOUNTING_CODES = "Accounting Codes"
    ACCOUNTS = "Accounts"
    CUSTOM_OBJECT_RECORDS = "Custom Object Records"
    INVOICE_SCHEDULES = "Invoice Schedules"
    PAYMENT_RUNS = "Payment Runs"
    PRODUCT_CHARGE_DEFINITIONS = "Product Charge Definitions"
    PRODUCT_RATE_PLANS = "Product Rate Plans"
    USAGE = "Usage"
    BILL_RUN = "Bill Run"
    METADATA = "Metadata"
    CUSTOM_OBJECT_JOBS = "Custom Object Jobs"
    SUMMARY_JOURNAL_ENTRIES = "Summary Journal Entries"
    ACTIONS = "Actions"
    DELIVERY_ADJUSTMENTS = "Delivery Adjustments"
    ATTACHMENTS = "Attachments"
    CATALOG_GROUPS = "Catalog Groups"
    CONTACTS = "Contacts"
    CUSTOM_EVENT_TRIGGERS = "Custom Event Triggers"
    CUSTOM_OBJECT_DEFINITIONS = "Custom Object Definitions"
    CUSTOM_PAYMENT_METHOD_TYPES = "Custom Payment Method Types"
    CUSTOM_SCHEDULED_EVENTS = "Custom Scheduled Events"
    OPERATIONS = "Operations"
    PRODUCT_RATE_PLAN_CHARGES = "Product Rate Plan Charges"
    RAMPS = "Ramps"
    SEQUENCE_SETS = "Sequence Sets"
    AGGREGATE_QUERIES = "Aggregate Queries"
    BILLING_DOCUMENTS = "Billing Documents"
    DATA_QUERIES = "Data Queries"
    JOURNAL_RUNS = "Journal Runs"
    PAYMENT_GATEWAY_RECONCILIATION = "Payment Gateway Reconciliation"
    PRODUCT_RATE_PLAN_DEFINITIONS = "Product Rate Plan Definitions"
    PRODUCTS = "Products"
    REGENERATE = "Regenerate"
    TAXATION_ITEMS = "Taxation Items"
    MASS_UPDATER = "Mass Updater"
    ORDER_LINE_ITEMS = "Order Line Items"
    PREPAID_WITH_DRAWDOWN = "Prepaid with Drawdown"
    BILLING_PREVIEW_RUN = "Billing Preview Run"
    CATALOG = "Catalog"
    DATA_LABELING = "Data Labeling"
    IMPORTS = "Imports"
    PAYMENT_METHOD_UPDATER = "Payment Method Updater"
    PAYMENT_AUTHORIZATION = "Payment Authorization"
    PRODUCT_RATE_PLAN_CHARGE_TIERS = "Product Rate Plan Charge Tiers"
    RSA_SIGNATURES = "RSA Signatures"
    SETTINGS = "Settings"
    API_HEALTH = "API Health"
    BILL_RUN_HEALTH = "Bill Run Health"
    CONTACT_SNAPSHOTS = "Contact Snapshots"
    CUSTOM_EXCHANGE_RATES = "Custom Exchange Rates"
    DESCRIBE = "Describe"
    ELECTRONIC_PAYMENTS_HEALTH = "Electronic Payments Health"
    FILES = "Files"
    HOSTED_PAGES = "Hosted Pages"
    OAUTH = "OAuth"
    ORDER_ACTIONS = "Order Actions"
    PAYMENT_GATEWAYS = "Payment Gateways"
    PAYMENT_METHOD_SNAPSHOTS = "Payment Method Snapshots"
    PAYMENT_METHOD_TRANSACTION_LOGS = "Payment Method Transaction Logs"
    PAYMENT_TRANSACTION_LOGS = "Payment Transaction Logs"
    RATE_PLANS = "Rate Plans"
    SIGN_UP = "Sign Up"
    ZUORA_REVENUE_INTEGRATION = "Zuora Revenue Integration"
